/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AddUserPatient = {
  /**
   * @type string | undefined
   */
  type?: string;
  /**
   * @type array | undefined
   */
  required?: string[];
  /**
   * @type object | undefined
   */
  properties?: {
    /**
     * @type object | undefined
     */
    userId?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
    /**
     * @type object | undefined
     */
    name?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
    /**
     * @type object | undefined
     */
    birthdayDate?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type number | undefined
       */
      example?: number;
    };
    /**
     * @type object | undefined
     */
    residentialAddress?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type array | undefined
       */
      required?: string[];
      /**
       * @type object | undefined
       */
      properties?: {
        /**
         * @type object | undefined
         */
        cep?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        endereco?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        bairro?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        numero?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        cidade?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        estado?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        complemento?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        name?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        type?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type array | undefined
           */
          enum?: string[];
          /**
           * @type string | undefined
           */
          example?: string;
        };
      };
    };
    /**
     * @type object | undefined
     */
    userSpecialties?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type object | undefined
       */
      items?: {
        /**
         * @type string | undefined
         */
        type?: string;
      };
      /**
       * @type array | undefined
       */
      example?: string[];
    };
    /**
     * @type object | undefined
     */
    userServicePreferences?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type object | undefined
       */
      items?: {
        /**
         * @type string | undefined
         */
        type?: string;
      };
      /**
       * @type array | undefined
       */
      example?: string[];
    };
    /**
     * @type object | undefined
     */
    accessibility?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type object | undefined
       */
      items?: {
        /**
         * @type string | undefined
         */
        type?: string;
      };
      /**
       * @type array | undefined
       */
      example?: string[];
      /**
       * @type string | undefined
       */
      description?: string;
    };
    /**
     * @type object | undefined
     */
    profilePhoto?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
  };
};
