/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const residentialAddressTypeEnum = {
  Casa: "Casa",
  Trabalho: "Trabalho",
  Outros: "Outros",
} as const;

export type ResidentialAddressTypeEnumKey =
  (typeof residentialAddressTypeEnum)[keyof typeof residentialAddressTypeEnum];

export type AddUserPatient = {
  /**
   * @type string
   */
  userId: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type number
   */
  birthdayDate: number;
  /**
   * @type object
   */
  residentialAddress: {
    /**
     * @type string
     */
    cep: string;
    /**
     * @type string
     */
    endereco: string;
    /**
     * @type string
     */
    bairro: string;
    /**
     * @type string
     */
    numero: string;
    /**
     * @type string
     */
    cidade: string;
    /**
     * @type string
     */
    estado: string;
    /**
     * @type string | undefined
     */
    complemento?: string;
    /**
     * @type string | undefined
     */
    name?: string;
    /**
     * @type string | undefined
     */
    type?: ResidentialAddressTypeEnumKey;
  };
  /**
   * @type array
   */
  userSpecialties: string[];
  /**
   * @type array
   */
  userServicePreferences: string[];
  /**
   * @description Preferências de acessibilidade do paciente (opcional)
   * @type array | undefined
   */
  accessibility?: string[];
  /**
   * @description URL da foto enviada anteriormente no upload
   * @type string | undefined
   */
  profilePhoto?: string;
};
