/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const residentialAddressTypeEnum2 = {
  Casa: "Casa",
  Trabalho: "Trabalho",
  Outros: "Outros",
} as const;

export type ResidentialAddressTypeEnum2Key =
  (typeof residentialAddressTypeEnum2)[keyof typeof residentialAddressTypeEnum2];

export type AddUserProfessional = {
  /**
   * @type string
   */
  userId: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type number
   */
  birthdayDate: number;
  /**
   * @type string
   */
  CNPJCPFProfissional: string;
  /**
   * @type object
   */
  residentialAddress: {
    /**
     * @type string
     */
    cep: string;
    /**
     * @type string
     */
    endereco: string;
    /**
     * @type string
     */
    bairro: string;
    /**
     * @description Opcional
     * @type string
     */
    numero: string;
    /**
     * @type string
     */
    cidade: string;
    /**
     * @type string
     */
    estado: string;
    /**
     * @type string | undefined
     */
    complemento?: string;
    /**
     * @type string | undefined
     */
    name?: string;
    /**
     * @type string | undefined
     */
    type?: ResidentialAddressTypeEnum2Key;
  };
  /**
   * @type object
   */
  clinic: {
    /**
     * @type string
     */
    name: string;
    /**
     * @type string
     */
    cep: string;
    /**
     * @type string
     */
    address: string;
    /**
     * @type string
     */
    neighborhood: string;
    /**
     * @type string
     */
    number: string;
    /**
     * @type string
     */
    city: string;
    /**
     * @type string
     */
    state: string;
    /**
     * @type string | undefined
     */
    addition?: string;
  };
  /**
   * @type array
   */
  professionalSpecialties: string[];
  /**
   * @type array
   */
  professionalServicePreferences: string[];
  /**
   * @description Opcional
   * @type array | undefined
   */
  otherProfessionalSpecialties?: string[];
  /**
   * @description Preferências de acessibilidade do profissional (opcional)
   * @type array | undefined
   */
  accessibility?: string[];
  /**
   * @description URL da foto enviada anteriormente no upload
   * @type string | undefined
   */
  profilePhoto?: string;
};
