/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AddUserProfessional = {
  /**
   * @type string | undefined
   */
  type?: string;
  /**
   * @type array | undefined
   */
  required?: string[];
  /**
   * @type object | undefined
   */
  properties?: {
    /**
     * @type object | undefined
     */
    userId?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
    /**
     * @type object | undefined
     */
    name?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
    /**
     * @type object | undefined
     */
    birthdayDate?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type number | undefined
       */
      example?: number;
    };
    /**
     * @type object | undefined
     */
    CNPJCPFProfissional?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
    /**
     * @type object | undefined
     */
    residentialAddress?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type array | undefined
       */
      required?: string[];
      /**
       * @type object | undefined
       */
      properties?: {
        /**
         * @type object | undefined
         */
        cep?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        address?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        neighborhood?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        city?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        state?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
      };
    };
    /**
     * @type object | undefined
     */
    clinic?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type array | undefined
       */
      required?: string[];
      /**
       * @type object | undefined
       */
      properties?: {
        /**
         * @type object | undefined
         */
        name?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        cep?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        address?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        neighborhood?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        number?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        city?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        state?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        addition?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
      };
    };
    /**
     * @type object | undefined
     */
    professionalSpecialties?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type object | undefined
       */
      items?: {
        /**
         * @type string | undefined
         */
        type?: string;
      };
      /**
       * @type array | undefined
       */
      example?: string[];
    };
    /**
     * @type object | undefined
     */
    professionalServicePreferences?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type object | undefined
       */
      items?: {
        /**
         * @type string | undefined
         */
        type?: string;
      };
      /**
       * @type array | undefined
       */
      example?: string[];
    };
    /**
     * @type object | undefined
     */
    otherProfessionalSpecialties?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type object | undefined
       */
      items?: {
        /**
         * @type string | undefined
         */
        type?: string;
      };
      /**
       * @type array | undefined
       */
      example?: string[];
      /**
       * @type string | undefined
       */
      description?: string;
    };
    /**
     * @type object | undefined
     */
    profilePhoto?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
  };
};
