/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Appointment = {
  /**
   * @type string | undefined
   */
  type?: string;
  /**
   * @type object | undefined
   */
  properties?: {
    /**
     * @type object | undefined
     */
    _id?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
    /**
     * @type object | undefined
     */
    patient?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
    /**
     * @type object | undefined
     */
    professional?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
    /**
     * @type object | undefined
     */
    dateTime?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      format?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
    /**
     * @type object | undefined
     */
    status?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
  };
};
