/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Appointment = {
  /**
   * @type string | undefined
   */
  _id?: string;
  /**
   * @type string | undefined
   */
  patient?: string;
  /**
   * @type string | undefined
   */
  professional?: string;
  /**
   * @type string | undefined, date-time
   */
  dateTime?: string;
  /**
   * @type string | undefined
   */
  status?: string;
};
