/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Body = {
  /**
   * @type string | undefined
   */
  type?: string;
  /**
   * @type array | undefined
   */
  required?: string[];
  /**
   * @type object | undefined
   */
  properties?: {
    /**
     * @type object | undefined
     */
    professionalId?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
    /**
     * @type object | undefined
     */
    notes?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
    /**
     * @type object | undefined
     */
    dateTime?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      format?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
    /**
     * @type object | undefined
     */
    address?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type array | undefined
       */
      required?: string[];
      /**
       * @type object | undefined
       */
      properties?: {
        /**
         * @type object | undefined
         */
        clinicId?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
          /**
           * @type string | undefined
           */
          description?: string;
        };
      };
    };
  };
};
