/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Banco de dados limpo com sucesso
 */
export type DeleteCleanup200 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Operação não permitida em produção ou com flag desativada
 */
export type DeleteCleanup403 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno ao limpar banco de dados
 */
export type DeleteCleanup500 = {
  /**
   * @type string | undefined
   */
  error?: string;
  /**
   * @type string | undefined
   */
  details?: string;
};

export type DeleteCleanupMutationResponse = DeleteCleanup200;

export type DeleteCleanupMutation = {
  Response: DeleteCleanup200;
  Errors: DeleteCleanup403 | DeleteCleanup500;
};
