/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Endereços encontrados com sucesso
 */
export type GetAddress200 = {
  /**
   * @type array | undefined
   */
  addresses?: {
    /**
     * @type string | undefined
     */
    _id?: string;
    /**
     * @type string | undefined
     */
    cep?: string;
    /**
     * @type string | undefined
     */
    endereco?: string;
    /**
     * @type string | undefined
     */
    bairro?: string;
    /**
     * @type string | undefined
     */
    estado?: string;
    /**
     * @type string | undefined
     */
    complemento?: string;
    /**
     * @type boolean | undefined
     */
    active?: boolean;
  }[];
};

/**
 * @description Não autorizado (token inválido ou ausente)
 */
export type GetAddress401 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Usuário não encontrado
 */
export type GetAddress404 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type GetAddress500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

export type GetAddressQueryResponse = GetAddress200;

export type GetAddressQuery = {
  Response: GetAddress200;
  Errors: GetAddress401 | GetAddress404 | GetAddress500;
};
