/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getAppointmentsMeQueryParamsSortEnum = {
  asc: "asc",
  desc: "desc",
} as const;

export type GetAppointmentsMeQueryParamsSortEnumKey =
  (typeof getAppointmentsMeQueryParamsSortEnum)[keyof typeof getAppointmentsMeQueryParamsSortEnum];

export type GetAppointmentsMeQueryParams = {
  /**
   * @description Filtra os agendamentos por status (pending, confirmed, completed, canceled ou all)
   * @type string | undefined
   */
  status?: string;
  /**
   * @description Data inicial do filtro (ISO 8601)
   * @type string | undefined, date-time
   */
  from?: string;
  /**
   * @description Data final do filtro (ISO 8601)
   * @type string | undefined, date-time
   */
  to?: string;
  /**
   * @description Número da página (default = 1)
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description Quantidade máxima por página (default = 20, max = 100)
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Ordenação por data do agendamento
   * @type string | undefined
   */
  sort?: GetAppointmentsMeQueryParamsSortEnumKey;
  /**
   * @type string | undefined
   */
  id?: string;
  /**
   * @type string | undefined
   */
  derivedStatus?: string;
  /**
   * @type string | undefined
   */
  dateTime?: string;
  /**
   * @type string | undefined
   */
  professional?: string;
  /**
   * @type string | undefined
   */
  patient?: string;
};

export type GetAppointmentsMeHeaderParams = {
  /**
   * @description Token JWT do paciente ou profissional (Bearer <token>)
   * @type string
   */
  authorization: string;
};

/**
 * @description Lista de agendamentos retornada com sucesso
 */
export type GetAppointmentsMe200 = {
  /**
   * @type object | undefined
   */
  meta?: {
    /**
     * @type number | undefined
     */
    page?: number;
    /**
     * @type number | undefined
     */
    limit?: number;
    /**
     * @type number | undefined
     */
    total?: number;
    /**
     * @type boolean | undefined
     */
    hasNextPage?: boolean;
  };
  /**
   * @type array | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    id?: string;
    /**
     * @type string | undefined
     */
    status?: string;
    /**
     * @type string | undefined
     */
    derivedStatus?: string;
    /**
     * @type string | undefined
     */
    dateTime?: string;
    /**
     * @type object | undefined
     */
    professional?: {
      /**
       * @type string | undefined
       */
      id?: string;
      /**
       * @type string | undefined
       */
      name?: string;
      /**
       * @type string | undefined
       */
      profileImageUrl?: string;
    };
    /**
     * @type object | undefined
     */
    patient?: {
      /**
       * @type string | undefined
       */
      id?: string;
      /**
       * @type string | undefined
       */
      name?: string;
    };
  }[];
};

/**
 * @description Usuário não autenticado
 */
export type GetAppointmentsMe401 = {
  /**
   * @type string | undefined
   */
  code?: string;
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Acesso Negado
 */
export type GetAppointmentsMe403 = any;

/**
 * @description Erro interno no servidor
 */
export type GetAppointmentsMe500 = {
  /**
   * @type string | undefined
   */
  code?: string;
  /**
   * @type string | undefined
   */
  error?: string;
};

export type GetAppointmentsMeQueryResponse = GetAppointmentsMe200;

export type GetAppointmentsMeQuery = {
  Response: GetAppointmentsMe200;
  QueryParams: GetAppointmentsMeQueryParams;
  HeaderParams: GetAppointmentsMeHeaderParams;
  Errors: GetAppointmentsMe401 | GetAppointmentsMe403 | GetAppointmentsMe500;
};
