/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetAppointmentsIdPathParams = {
  /**
   * @description ID do agendamento
   * @type string
   */
  id: string;
};

export type GetAppointmentsIdHeaderParams = {
  /**
   * @description Token JWT do paciente ou profissional (Bearer <token>)
   * @type string
   */
  authorization: string;
};

/**
 * @description Detalhes do agendamento retornados com sucesso
 */
export type GetAppointmentsId200 = {
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    id?: string;
    /**
     * @type string | undefined
     */
    status?: string;
    /**
     * @type string | undefined
     */
    dateTime?: string;
    /**
     * @type object | undefined
     */
    professional?: {
      /**
       * @type string | undefined
       */
      id?: string;
      /**
       * @type string | undefined
       */
      photoUrl?: string;
      /**
       * @type string | undefined
       */
      name?: string;
      distanceKm?: any;
      /**
       * @type array | undefined
       */
      specialties?: string[];
    };
    /**
     * @type string | undefined
     */
    yourObservation?: string;
    /**
     * @type string | undefined
     */
    selectedAddress?: string;
  };
};

/**
 * @description ID inválido
 */
export type GetAppointmentsId400 = {
  /**
   * @type string | undefined
   */
  code?: string;
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Usuário não autenticado
 */
export type GetAppointmentsId401 = {
  /**
   * @type string | undefined
   */
  code?: string;
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Usuário não tem permissão para acessar este agendamento
 */
export type GetAppointmentsId403 = {
  /**
   * @type string | undefined
   */
  code?: string;
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Agendamento não encontrado
 */
export type GetAppointmentsId404 = {
  /**
   * @type string | undefined
   */
  code?: string;
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type GetAppointmentsId500 = {
  /**
   * @type string | undefined
   */
  code?: string;
  /**
   * @type string | undefined
   */
  error?: string;
};

export type GetAppointmentsIdQueryResponse = GetAppointmentsId200;

export type GetAppointmentsIdQuery = {
  Response: GetAppointmentsId200;
  PathParams: GetAppointmentsIdPathParams;
  HeaderParams: GetAppointmentsIdHeaderParams;
  Errors:
    | GetAppointmentsId400
    | GetAppointmentsId401
    | GetAppointmentsId403
    | GetAppointmentsId404
    | GetAppointmentsId500;
};
