/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetMessagesUnreadHeaderParams = {
  /**
   * @description Token JWT — formato: Bearer <token>
   * @type string
   */
  authorization: string;
};

/**
 * @description Lista de conversas com mensagens não lidas retornada com sucesso
 */
export type GetMessagesUnread200 = {
  /**
   * @type array | undefined
   */
  items?: {
    /**
     * @type string | undefined
     */
    conversation?: string;
    /**
     * @type string | undefined
     */
    otherId?: string;
    /**
     * @type string | undefined
     */
    otherName?: string;
    /**
     * @type string | undefined
     */
    otherAvatar?: string;
    /**
     * @type object | undefined
     */
    lastMessage?: {
      /**
       * @type string | undefined
       */
      content?: string;
      /**
       * @type string | undefined
       */
      sender?: string;
      /**
       * @type string | undefined
       */
      createdAt?: string;
    };
    /**
     * @type number | undefined
     */
    unreadCount?: number;
  }[];
};

/**
 * @description Usuário não autenticado
 */
export type GetMessagesUnread401 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Acesso Negado
 */
export type GetMessagesUnread403 = any;

/**
 * @description Erro interno no servidor
 */
export type GetMessagesUnread500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

export type GetMessagesUnreadQueryResponse = GetMessagesUnread200;

export type GetMessagesUnreadQuery = {
  Response: GetMessagesUnread200;
  HeaderParams: GetMessagesUnreadHeaderParams;
  Errors: GetMessagesUnread401 | GetMessagesUnread403 | GetMessagesUnread500;
};
