/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetMessagesContactsHeaderParams = {
  /**
   * @description Token JWT — formato: Bearer <token>
   * @type string
   */
  authorization: string;
};

/**
 * @description Contatos listados com sucesso
 */
export type GetMessagesContacts200 = {
  /**
   * @type array | undefined
   */
  items?: {
    /**
     * @type string | undefined
     */
    conversation?: string;
    /**
     * @type string | undefined
     */
    contactId?: string;
    /**
     * @type string | undefined
     */
    contactName?: string;
    /**
     * @type string | undefined
     */
    contactAvatar?: string;
    /**
     * @type string | undefined
     */
    userType?: string;
    /**
     * @type object | undefined
     */
    lastMessage?: {
      /**
       * @type string | undefined
       */
      content?: string;
      /**
       * @type string | undefined
       */
      sender?: string;
      /**
       * @type string | undefined
       */
      createdAt?: string;
    };
    /**
     * @type number | undefined
     */
    unreadCount?: number;
  }[];
};

/**
 * @description Usuário não autenticado
 */
export type GetMessagesContacts401 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Acesso Negado
 */
export type GetMessagesContacts403 = any;

/**
 * @description Erro interno no servidor
 */
export type GetMessagesContacts500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

export type GetMessagesContactsQueryResponse = GetMessagesContacts200;

export type GetMessagesContactsQuery = {
  Response: GetMessagesContacts200;
  HeaderParams: GetMessagesContactsHeaderParams;
  Errors:
    | GetMessagesContacts401
    | GetMessagesContacts403
    | GetMessagesContacts500;
};
