/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetSearchSearchbarTermsPathParams = {
  /**
   * @description Termo de busca (nome ou especialidade do profissional)
   * @type string
   */
  terms: string;
  /**
   * @description Número da página para paginação (cada página retorna até 10 profissionais)
   * @type integer
   */
  page: number;
};

/**
 * @description Profissionais encontrados com sucesso
 */
export type GetSearchSearchbarTerms200 = {
  /**
   * @type array | undefined
   */
  professionals?: {
    /**
     * @type string | undefined
     */
    _id?: string;
    /**
     * @type string | undefined
     */
    name?: string;
    /**
     * @type string | undefined
     */
    birthdayDate?: string;
    /**
     * @type string | undefined
     */
    clinic?: string;
    /**
     * @type string | undefined
     */
    residentialAddress?: string;
    /**
     * @type string | undefined
     */
    phoneNumber?: string;
    /**
     * @type array | undefined
     */
    professionalSpecialties?: string[];
    /**
     * @type string | undefined
     */
    profilePhoto?: string;
  }[];
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  pageCount?: number;
};

/**
 * @description Requisição inválida (parâmetros ausentes ou página inválida)
 */
export type GetSearchSearchbarTerms400 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type GetSearchSearchbarTerms500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

export type GetSearchSearchbarTermsQueryResponse = GetSearchSearchbarTerms200;

export type GetSearchSearchbarTermsQuery = {
  Response: GetSearchSearchbarTerms200;
  PathParams: GetSearchSearchbarTermsPathParams;
  Errors: GetSearchSearchbarTerms400 | GetSearchSearchbarTerms500;
};
