/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetSearchHighlightsweekPathParams = {
  /**
   * @description Número da página para paginação (cada página retorna até 10 profissionais)
   * @type integer
   */
  page: number;
};

/**
 * @description Profissionais encontrados com sucesso
 */
export type GetSearchHighlightsweek200 = {
  /**
   * @type array | undefined
   */
  professionals?: {
    /**
     * @type string | undefined
     */
    _id?: string;
    /**
     * @type string | undefined
     */
    name?: string;
    /**
     * @type string | undefined
     */
    birthdayDate?: string;
    /**
     * @type string | undefined
     */
    clinic?: string;
    /**
     * @type string | undefined
     */
    residentialAddress?: string;
    /**
     * @type string | undefined
     */
    phoneNumber?: string;
    /**
     * @type string | undefined
     */
    profilePhoto?: string;
  }[];
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  pageCount?: number;
};

/**
 * @description Página inválida
 */
export type GetSearchHighlightsweek400 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type GetSearchHighlightsweek500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

export type GetSearchHighlightsweekQueryResponse = GetSearchHighlightsweek200;

export type GetSearchHighlightsweekQuery = {
  Response: GetSearchHighlightsweek200;
  PathParams: GetSearchHighlightsweekPathParams;
  Errors: GetSearchHighlightsweek400 | GetSearchHighlightsweek500;
};
