/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetSearchProfessionalbyspecialitySpecialityPathParams = {
  /**
   * @description Especialidade a ser pesquisada
   * @type string
   */
  speciality: string;
  /**
   * @description Número da página para paginação (cada página retorna até 10 profissionais)
   * @type integer
   */
  page: number;
};

/**
 * @description Profissionais encontrados com sucesso
 */
export type GetSearchProfessionalbyspecialitySpeciality200 = {
  /**
   * @type array | undefined
   */
  professionals?: {
    /**
     * @type string | undefined
     */
    _id?: string;
    /**
     * @type string | undefined
     */
    name?: string;
    /**
     * @type string | undefined
     */
    birthdayDate?: string;
    /**
     * @type string | undefined
     */
    clinic?: string;
    /**
     * @type string | undefined
     */
    residentialAddress?: string;
    /**
     * @type string | undefined
     */
    phoneNumber?: string;
    /**
     * @type array | undefined
     */
    professionalSpecialties?: string[];
    /**
     * @type string | undefined
     */
    profilePhoto?: string;
  }[];
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  pageCount?: number;
};

/**
 * @description Requisição inválida (falta de parâmetros ou página inválida)
 */
export type GetSearchProfessionalbyspecialitySpeciality400 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type GetSearchProfessionalbyspecialitySpeciality500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

export type GetSearchProfessionalbyspecialitySpecialityQueryResponse =
  GetSearchProfessionalbyspecialitySpeciality200;

export type GetSearchProfessionalbyspecialitySpecialityQuery = {
  Response: GetSearchProfessionalbyspecialitySpeciality200;
  PathParams: GetSearchProfessionalbyspecialitySpecialityPathParams;
  Errors:
    | GetSearchProfessionalbyspecialitySpeciality400
    | GetSearchProfessionalbyspecialitySpeciality500;
};
