/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetSearchProfessionalIdPathParams = {
  /**
   * @description ID do profissional
   * @type string
   */
  id: string;
};

/**
 * @description Profissional encontrado
 */
export type GetSearchProfessionalId200 = {
  /**
   * @type string | undefined
   */
  _id?: string;
  /**
   * @type string | undefined
   */
  name?: string;
  /**
   * @type string | undefined
   */
  imageUrl?: string;
  /**
   * @type array | undefined
   */
  professionalSpecialties?: string[];
  /**
   * @type array | undefined
   */
  professionalServicePreferences?: string[];
  /**
   * @type object | undefined
   */
  clinic?: {
    /**
     * @type string | undefined
     */
    name?: string;
    /**
     * @type string | undefined
     */
    city?: string;
    /**
     * @type string | undefined
     */
    state?: string;
  };
  /**
   * @type object | undefined
   */
  location?: {
    /**
     * @type string | undefined
     */
    city?: string;
    /**
     * @type string | undefined
     */
    state?: string;
  };
};

/**
 * @description Solicitação Inválida
 */
export type GetSearchProfessionalId400 = any;

/**
 * @description Profissional não encontrado
 */
export type GetSearchProfessionalId404 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno
 */
export type GetSearchProfessionalId500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

export type GetSearchProfessionalIdQueryResponse = GetSearchProfessionalId200;

export type GetSearchProfessionalIdQuery = {
  Response: GetSearchProfessionalId200;
  PathParams: GetSearchProfessionalIdPathParams;
  Errors:
    | GetSearchProfessionalId400
    | GetSearchProfessionalId404
    | GetSearchProfessionalId500;
};
