/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Lista de especialidades retornada com sucesso
 */
export type GetSpecialties200 = {
  /**
   * @type string | undefined
   */
  id?: string;
  /**
   * @type string | undefined
   */
  name?: string;
}[];

/**
 * @description Erro interno no servidor
 */
export type GetSpecialties500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

export type GetSpecialtiesQueryResponse = GetSpecialties200;

export type GetSpecialtiesQuery = {
  Response: GetSpecialties200;
  Errors: GetSpecialties500;
};
