/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetSearchProfessionalsQueryParams = {
  /**
   * @description Especialidade do profissional. Pode ser repetido para filtrar por múltiplas especialidades (ex: ?specialty=Reiki&specialty=Acupuntura). Match com OR dentro do filtro.
   * @type array | undefined
   */
  specialty?: any[];
  /**
   * @description Tipo de serviço oferecido. Pode ser repetido para múltiplos serviços (ex: ?service=Pet+Friendly&service=LGBTQIAP%2B+Friendly). Match com OR.
   * @type array | undefined
   */
  service?: any[];
  /**
   * @description Filtro de acessibilidade oferecida pelo profissional. Pode ser repetido para múltiplos itens (ex: ?accessibility=Libras&accessibility=Rampas). Match com OR.
   * @type array | undefined
   */
  accessibility?: any[];
  /**
   * @description Número da página
   * @type integer | undefined
   */
  page?: number;
  /**
   * @type string | undefined
   */
  in?: string;
  /**
   * @type string | undefined
   */
  description?: string;
  /**
   * @type string | undefined
   */
  required?: string;
  /**
   * @type string | undefined
   */
  type?: string;
  /**
   * @type string | undefined
   */
  collectionFormat?: string;
  /**
   * @type string | undefined
   */
  items?: string;
  /**
   * @type string | undefined
   */
  example?: string;
};

/**
 * @description Profissionais encontrados com sucesso
 */
export type GetSearchProfessionals200 = any;

/**
 * @description Erro interno no servidor
 */
export type GetSearchProfessionals500 = any;

export type GetSearchProfessionalsQueryResponse = GetSearchProfessionals200;

export type GetSearchProfessionalsQuery = {
  Response: GetSearchProfessionals200;
  QueryParams: GetSearchProfessionalsQueryParams;
  Errors: GetSearchProfessionals500;
};
