/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetSearchProfessionalsQueryParams = {
  /**
   * @description Especialidade do profissional
   * @type string | undefined
   */
  specialty?: string;
  /**
   * @description Tipo de serviço oferecido
   * @type string | undefined
   */
  service?: string;
  /**
   * @description Número da página
   * @type integer | undefined
   */
  page?: number;
};

/**
 * @description Profissionais encontrados com sucesso
 */
export type GetSearchProfessionals200 = any;

/**
 * @description Erro interno no servidor
 */
export type GetSearchProfessionals500 = any;

export type GetSearchProfessionalsQueryResponse = GetSearchProfessionals200;

export type GetSearchProfessionalsQuery = {
  Response: GetSearchProfessionals200;
  QueryParams: GetSearchProfessionalsQueryParams;
  Errors: GetSearchProfessionals500;
};
