/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetTeste200 = any;

export type GetTesteQueryResponse = GetTeste200;

export type GetTesteQuery = {
  Response: GetTeste200;
  Errors: any;
};
