/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetUserHeaderParams = {
  /**
   * @description Token JWT do paciente ou profissional (Bearer <token>)
   * @type string
   */
  authorization: string;
};

/**
 * @description Usuário encontrado, dados retornados com sucesso
 */
export type GetUser200 = {
  /**
   * @type string | undefined
   */
  _id?: string;
  /**
   * @type string | undefined
   */
  name?: string;
  /**
   * @type string | undefined
   */
  email?: string;
  /**
   * @type string | undefined
   */
  status?: string;
  /**
   * @type array | undefined
   */
  userType?: string[];
  /**
   * @type string | undefined
   */
  imageUrl?: string;
  /**
   * @type object | undefined
   */
  residentialAddress?: {
    /**
     * @type string | undefined
     */
    cep?: string;
    /**
     * @type string | undefined
     */
    endereco?: string;
    /**
     * @type string | undefined
     */
    bairro?: string;
    /**
     * @type string | undefined
     */
    cidade?: string;
    /**
     * @type string | undefined
     */
    estado?: string;
    /**
     * @type string | undefined
     */
    type?: string;
  };
};

/**
 * @description Não autorizado
 */
export type GetUser401 = any;

/**
 * @description Acesso Negado
 */
export type GetUser403 = any;

/**
 * @description Não Encontrado
 */
export type GetUser404 = any;

/**
 * @description Erro Interno do Servidor
 */
export type GetUser500 = any;

export type GetUserQueryResponse = GetUser200;

export type GetUserQuery = {
  Response: GetUser200;
  HeaderParams: GetUserHeaderParams;
  Errors: GetUser401 | GetUser403 | GetUser404 | GetUser500;
};
