/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PatchConversationsConversationidReadPathParams = {
  /**
   * @description Identificador único da conversa
   * @type string
   */
  conversationId: string;
};

export type PatchConversationsConversationidReadHeaderParams = {
  /**
   * @description Token JWT — formato: Bearer <token>
   * @type string
   */
  authorization: string;
};

/**
 * @description Conversa marcada como lida (sem conteúdo de resposta)
 */
export type PatchConversationsConversationidRead204 = any;

/**
 * @description Usuário não autenticado
 */
export type PatchConversationsConversationidRead401 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Usuário não participa da conversa
 */
export type PatchConversationsConversationidRead403 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Conversa não encontrada
 */
export type PatchConversationsConversationidRead404 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type PatchConversationsConversationidRead500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

export type PatchConversationsConversationidReadMutationResponse =
  PatchConversationsConversationidRead204;

export type PatchConversationsConversationidReadMutation = {
  Response: PatchConversationsConversationidRead204;
  PathParams: PatchConversationsConversationidReadPathParams;
  HeaderParams: PatchConversationsConversationidReadHeaderParams;
  Errors:
    | PatchConversationsConversationidRead401
    | PatchConversationsConversationidRead403
    | PatchConversationsConversationidRead404
    | PatchConversationsConversationidRead500;
};
