/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Códigos OTP coincidem e login/registro autorizado
 */
export type PostAuthCheckotp200 = {
  /**
   * @type string | undefined
   */
  id?: string;
  /**
   * @type string | undefined
   */
  email?: string;
  /**
   * @type string | undefined
   */
  status?: string;
  /**
   * @type string | undefined
   */
  token?: string;
};

/**
 * @description Códigos OTP não coincidem
 */
export type PostAuthCheckotp401 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Parâmetros obrigatórios não enviados
 */
export type PostAuthCheckotp422 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Erro interno no servidor
 */
export type PostAuthCheckotp500 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description E-mail do usuário e OTP recebido
 */
export type PostAuthCheckotpMutationRequest = {
  /**
   * @type string | undefined
   */
  email?: string;
  /**
   * @type string | undefined
   */
  OTP?: string;
};

export type PostAuthCheckotpMutationResponse = PostAuthCheckotp200;

export type PostAuthCheckotpMutation = {
  Response: PostAuthCheckotp200;
  Request: PostAuthCheckotpMutationRequest;
  Errors: PostAuthCheckotp401 | PostAuthCheckotp422 | PostAuthCheckotp500;
};
