/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostAppointmentsHeaderParams = {
  /**
   * @description Token JWT do paciente — formato: Bearer <token>
   * @type string
   */
  authorization: string;
};

/**
 * @description Solicitação criada com sucesso
 */
export type PostAppointments201 = {
  /**
   * @type string | undefined
   */
  message?: string;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    id?: string;
    /**
     * @type string | undefined
     */
    status?: string;
    /**
     * @type string | undefined
     */
    dateTime?: string;
  };
};

/**
 * @description Campos obrigatórios ausentes ou inválidos
 */
export type PostAppointments400 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Paciente não autorizado (JWT inválido ou ausente)
 */
export type PostAppointments401 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Acesso Negado
 */
export type PostAppointments403 = any;

/**
 * @description Horário já ocupado
 */
export type PostAppointments409 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Tentativa inválida (agendamento no passado ou paciente = profissional)
 */
export type PostAppointments422 = {
  /**
   * @type string | undefined
   */
  code?: string;
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type PostAppointments500 = {
  /**
   * @type string | undefined
   */
  code?: string;
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Dados necessários para criar um agendamento
 */
export type PostAppointmentsMutationRequest = {
  /**
   * @description ID do profissional com quem o paciente deseja agendar
   * @type string
   */
  professionalId: string;
  /**
   * @description Observações adicionais para o profissional
   * @type string | undefined
   */
  notes?: string;
  /**
   * @description Data/hora do agendamento no formato ISO 8601
   * @type string, date-time
   */
  dateTime: string;
  /**
   * @type object
   */
  address: {
    /**
     * @description ID da clínica/endereço onde ocorrerá o atendimento
     * @type string
     */
    clinicId: string;
  };
};

export type PostAppointmentsMutationResponse = PostAppointments201;

export type PostAppointmentsMutation = {
  Response: PostAppointments201;
  Request: PostAppointmentsMutationRequest;
  HeaderParams: PostAppointmentsHeaderParams;
  Errors:
    | PostAppointments400
    | PostAppointments401
    | PostAppointments403
    | PostAppointments409
    | PostAppointments422
    | PostAppointments500;
};
