/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostAppointmentsIdActionsPathParams = {
  /**
   * @type string
   */
  id: string;
};

export type PostAppointmentsIdActionsHeaderParams = {
  /**
   * @description Token JWT do paciente — formato: Bearer <token>
   * @type string
   */
  authorization: string;
};

/**
 * @description OK
 */
export type PostAppointmentsIdActions200 = any;

/**
 * @description Solicitação criada com sucesso
 */
export type PostAppointmentsIdActions201 = {
  /**
   * @type string | undefined
   */
  message?: string;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    id?: string;
    /**
     * @type string | undefined
     */
    status?: string;
    /**
     * @type string | undefined
     */
    dateTime?: string;
  };
};

/**
 * @description Campos obrigatórios ausentes ou inválidos
 */
export type PostAppointmentsIdActions400 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Paciente não autorizado (JWT inválido ou ausente)
 */
export type PostAppointmentsIdActions401 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Acesso Negado
 */
export type PostAppointmentsIdActions403 = any;

/**
 * @description Não Encontrado
 */
export type PostAppointmentsIdActions404 = any;

/**
 * @description Horário já ocupado
 */
export type PostAppointmentsIdActions409 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Tentativa inválida (agendamento no passado ou paciente = profissional)
 */
export type PostAppointmentsIdActions422 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type PostAppointmentsIdActions500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Dados necessários para criar um agendamento
 */
export type PostAppointmentsIdActionsMutationRequest = {
  /**
   * @description ID do profissional com quem o paciente deseja agendar
   * @type string
   */
  professionalId: string;
  /**
   * @description Observações adicionais para o profissional
   * @type string | undefined
   */
  notes?: string;
  /**
   * @description Data/hora do agendamento no formato ISO 8601
   * @type string, date-time
   */
  dateTime: string;
  /**
   * @type object
   */
  address: {
    /**
     * @description ID da clínica/endereço onde ocorrerá o atendimento
     * @type string
     */
    clinicId: string;
  };
};

export type PostAppointmentsIdActionsMutationResponse =
  | PostAppointmentsIdActions200
  | PostAppointmentsIdActions201;

export type PostAppointmentsIdActionsMutation = {
  Response: PostAppointmentsIdActions200 | PostAppointmentsIdActions201;
  Request: PostAppointmentsIdActionsMutationRequest;
  PathParams: PostAppointmentsIdActionsPathParams;
  HeaderParams: PostAppointmentsIdActionsHeaderParams;
  Errors:
    | PostAppointmentsIdActions400
    | PostAppointmentsIdActions401
    | PostAppointmentsIdActions403
    | PostAppointmentsIdActions404
    | PostAppointmentsIdActions409
    | PostAppointmentsIdActions422
    | PostAppointmentsIdActions500;
};
