/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostAuthUploadphotoHeaderParams = {
  /**
   * @description Token JWT do usuário — formato: Bearer <token>
   * @type string
   */
  authorization: string;
};

/**
 * @description Foto enviada com sucesso
 */
export type PostAuthUploadphoto201 = {
  /**
   * @type string | undefined
   */
  msg?: string;
  /**
   * @type string | undefined
   */
  imageUrl?: string;
};

/**
 * @description Requisição inválida
 */
export type PostAuthUploadphoto400 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Não autorizado
 */
export type PostAuthUploadphoto401 = any;

/**
 * @description Acesso Negado
 */
export type PostAuthUploadphoto403 = any;

/**
 * @description Usuário não encontrado
 */
export type PostAuthUploadphoto404 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro de validação
 */
export type PostAuthUploadphoto422 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno ao enviar imagem
 */
export type PostAuthUploadphoto500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

export type PostAuthUploadphotoMutationResponse = PostAuthUploadphoto201;

export type PostAuthUploadphotoMutation = {
  Response: PostAuthUploadphoto201;
  HeaderParams: PostAuthUploadphotoHeaderParams;
  Errors:
    | PostAuthUploadphoto400
    | PostAuthUploadphoto401
    | PostAuthUploadphoto403
    | PostAuthUploadphoto404
    | PostAuthUploadphoto422
    | PostAuthUploadphoto500;
};
