/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddUserProfessional } from "./AddUserProfessional.ts";

export type PostAuthCreateprofessionalHeaderParams = {
  /**
   * @type string | undefined
   */
  authorization?: string;
};

/**
 * @description Usuário encontrado, mas nenhuma alteração realizada
 */
export type PostAuthCreateprofessional200 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Usuário encontrado e cadastro completado com sucesso
 */
export type PostAuthCreateprofessional201 = {
  /**
   * @type string | undefined
   */
  msg?: string;
  /**
   * @type string | undefined
   */
  token?: string;
};

/**
 * @description Não autorizado
 */
export type PostAuthCreateprofessional401 = any;

/**
 * @description Acesso Negado
 */
export type PostAuthCreateprofessional403 = any;

/**
 * @description Usuário não encontrado
 */
export type PostAuthCreateprofessional404 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Parâmetros obrigatórios não enviados ou inválidos
 */
export type PostAuthCreateprofessional422 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type PostAuthCreateprofessional500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Dados obrigatórios para completar o cadastro do profissional. Necessário ter passado antes por sendOTP e checkOTP.
 */
export type PostAuthCreateprofessionalMutationRequest = AddUserProfessional;

export type PostAuthCreateprofessionalMutationResponse =
  | PostAuthCreateprofessional200
  | PostAuthCreateprofessional201;

export type PostAuthCreateprofessionalMutation = {
  Response: PostAuthCreateprofessional200 | PostAuthCreateprofessional201;
  Request: PostAuthCreateprofessionalMutationRequest;
  HeaderParams: PostAuthCreateprofessionalHeaderParams;
  Errors:
    | PostAuthCreateprofessional401
    | PostAuthCreateprofessional403
    | PostAuthCreateprofessional404
    | PostAuthCreateprofessional422
    | PostAuthCreateprofessional500;
};
