/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostMessagesHeaderParams = {
  /**
   * @description Token JWT — formato: Bearer <token>
   * @type string
   */
  authorization: string;
};

/**
 * @description Mensagem criada com sucesso
 */
export type PostMessages201 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  messageId?: string;
  /**
   * @type string | undefined
   */
  conversation?: string;
};

/**
 * @description Parâmetros obrigatórios ausentes ou inválidos
 */
export type PostMessages400 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Usuário não autenticado (JWT ausente ou inválido)
 */
export type PostMessages401 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Acesso Negado
 */
export type PostMessages403 = any;

/**
 * @description Erro interno no servidor
 */
export type PostMessages500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Dados da mensagem a ser enviada
 */
export type PostMessagesMutationRequest = {
  /**
   * @description Identificador único da conversa. Opcional — se não enviado, será criado automaticamente.
   * @type string | undefined
   */
  conversation?: string;
  /**
   * @description Conteúdo da mensagem enviada
   * @type string
   */
  content: string;
  /**
   * @description Lista de participantes da conversa. Obrigatório se conversation não for informado.
   * @type array | undefined
   */
  participants?: string[];
};

export type PostMessagesMutationResponse = PostMessages201;

export type PostMessagesMutation = {
  Response: PostMessages201;
  Request: PostMessagesMutationRequest;
  HeaderParams: PostMessagesHeaderParams;
  Errors: PostMessages400 | PostMessages401 | PostMessages403 | PostMessages500;
};
