/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { WebhookMessageCreated } from "./WebhookMessageCreated.ts";

export type PostWebhooksMessageCreatedHeaderParams = {
  /**
   * @description Tipo do evento
   * @type string
   */
  "X-Event-Type": string;
  /**
   * @description UUID único do evento
   * @type string
   */
  "X-Event-Id": string;
  /**
   * @description Assinatura HMAC SHA-256 do corpo com WEBHOOK_SECRET
   * @type string
   */
  "X-Signature-SHA256": string;
};

/**
 * @description Exemplo de payload recebido pelo webhook
 */
export type PostWebhooksMessageCreated200 = {
  /**
   * @type string | undefined
   */
  eventId?: string;
  /**
   * @type string | undefined
   */
  type?: string;
  /**
   * @type string | undefined
   */
  occurredAt?: string;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    messageId?: string;
    /**
     * @type string | undefined
     */
    conversation?: string;
    /**
     * @type string | undefined
     */
    sender?: string;
    /**
     * @type string | undefined
     */
    senderName?: string;
    /**
     * @type string | undefined
     */
    content?: string;
    /**
     * @type string | undefined
     */
    createdAt?: string;
  };
};

/**
 * @description Assinatura inválida
 */
export type PostWebhooksMessageCreated401 = any;

export type PostWebhooksMessageCreatedMutationRequest = WebhookMessageCreated;

export type PostWebhooksMessageCreatedMutationResponse =
  PostWebhooksMessageCreated200;

export type PostWebhooksMessageCreatedMutation = {
  Response: PostWebhooksMessageCreated200;
  Request: PostWebhooksMessageCreatedMutationRequest;
  HeaderParams: PostWebhooksMessageCreatedHeaderParams;
  Errors: PostWebhooksMessageCreated401;
};
