/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddUserPatient } from "./AddUserPatient.ts";

export type PostAuthCreatepatientHeaderParams = {
  /**
   * @type string | undefined
   */
  authorization?: string;
};

/**
 * @description Usuário encontrado, mas nenhuma alteração realizada
 */
export type PostAuthCreatepatient200 = {
  /**
   * @type string | undefined
   */
  msg?: string;
};

/**
 * @description Usuário encontrado e cadastro completado com sucesso
 */
export type PostAuthCreatepatient201 = {
  /**
   * @type string | undefined
   */
  msg?: string;
  /**
   * @type string | undefined
   */
  token?: string;
};

/**
 * @description Não autorizado
 */
export type PostAuthCreatepatient401 = any;

/**
 * @description Acesso Negado
 */
export type PostAuthCreatepatient403 = any;

/**
 * @description Usuário não encontrado
 */
export type PostAuthCreatepatient404 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Parâmetros obrigatórios não enviados ou inválidos
 */
export type PostAuthCreatepatient422 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type PostAuthCreatepatient500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Dados obrigatórios para completar o cadastro do paciente. Necessário ter passado antes por sendOTP e checkOTP.
 */
export type PostAuthCreatepatientMutationRequest = AddUserPatient;

export type PostAuthCreatepatientMutationResponse =
  | PostAuthCreatepatient200
  | PostAuthCreatepatient201;

export type PostAuthCreatepatientMutation = {
  Response: PostAuthCreatepatient200 | PostAuthCreatepatient201;
  Request: PostAuthCreatepatientMutationRequest;
  HeaderParams: PostAuthCreatepatientHeaderParams;
  Errors:
    | PostAuthCreatepatient401
    | PostAuthCreatepatient403
    | PostAuthCreatepatient404
    | PostAuthCreatepatient422
    | PostAuthCreatepatient500;
};
