/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Usuário já existente, OTP atualizado e enviado por e-mail
 */
export type PostAuthSendotp200 = {
  /**
   * @type string | undefined
   */
  id?: string;
  /**
   * @type object | undefined
   */
  email?: {
    /**
     * @type string | undefined
     */
    address?: string;
    /**
     * @type boolean | undefined
     */
    exists?: boolean;
    /**
     * @type string | undefined
     */
    status?: string;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Usuário criado com sucesso e OTP enviado por e-mail
 */
export type PostAuthSendotp201 = {
  /**
   * @type string | undefined
   */
  id?: string;
  /**
   * @type object | undefined
   */
  email?: {
    /**
     * @type string | undefined
     */
    address?: string;
    /**
     * @type boolean | undefined
     */
    exists?: boolean;
    /**
     * @type string | undefined
     */
    status?: string;
  };
  role?: any;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Parâmetros inválidos ou não enviados
 */
export type PostAuthSendotp422 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Muitas tentativas. Tente novamente em 15 minutos.
 */
export type PostAuthSendotp429 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Erro interno no servidor
 */
export type PostAuthSendotp500 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description E-mail do usuário para envio do OTP
 */
export type PostAuthSendotpMutationRequest = {
  /**
   * @type string
   */
  email: string;
};

export type PostAuthSendotpMutationResponse =
  | PostAuthSendotp200
  | PostAuthSendotp201;

export type PostAuthSendotpMutation = {
  Response: PostAuthSendotp200 | PostAuthSendotp201;
  Request: PostAuthSendotpMutationRequest;
  Errors: PostAuthSendotp422 | PostAuthSendotp429 | PostAuthSendotp500;
};
