/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Foto enviada com sucesso
 */
export type PostAuthUploadphoto201 = {
  /**
   * @type string | undefined
   */
  msg?: string;
  /**
   * @type string | undefined
   */
  imageUrl?: string;
};

/**
 * @description Requisição inválida
 */
export type PostAuthUploadphoto400 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro de validação
 */
export type PostAuthUploadphoto422 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno ao enviar imagem
 */
export type PostAuthUploadphoto500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

export type PostAuthUploadphotoMutationResponse = PostAuthUploadphoto201;

export type PostAuthUploadphotoMutation = {
  Response: PostAuthUploadphoto201;
  Errors:
    | PostAuthUploadphoto400
    | PostAuthUploadphoto422
    | PostAuthUploadphoto500;
};
