/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutActiveAddressHeaderParams = {
  /**
   * @type string | undefined
   */
  authorization?: string;
};

/**
 * @description Endereço principal atualizado com sucesso
 */
export type PutActiveAddress200 = {
  /**
   * @type string | undefined
   */
  msg?: string;
};

/**
 * @description Não houve alteração no endereço principal
 */
export type PutActiveAddress304 = {
  /**
   * @type string | undefined
   */
  msg?: string;
};

/**
 * @description Não autorizado
 */
export type PutActiveAddress401 = any;

/**
 * @description Acesso Negado
 */
export type PutActiveAddress403 = any;

/**
 * @description Usuário não encontrado
 */
export type PutActiveAddress404 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description ID do endereço não fornecido
 */
export type PutActiveAddress422 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type PutActiveAddress500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description ID do endereço que será definido como principal
 */
export type PutActiveAddressMutationRequest = {
  /**
   * @description ID do endereço a ser definido como principal
   * @type string
   */
  addressId: string;
};

export type PutActiveAddressMutationResponse = PutActiveAddress200;

export type PutActiveAddressMutation = {
  Response: PutActiveAddress200;
  Request: PutActiveAddressMutationRequest;
  HeaderParams: PutActiveAddressHeaderParams;
  Errors:
    | PutActiveAddress401
    | PutActiveAddress403
    | PutActiveAddress404
    | PutActiveAddress422
    | PutActiveAddress500;
};
