/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Endereço principal atualizado com sucesso
 */
export type PutActiveAddress200 = {
  /**
   * @type string | undefined
   */
  msg?: string;
};

/**
 * @description Não houve alteração no endereço principal
 */
export type PutActiveAddress304 = {
  /**
   * @type string | undefined
   */
  msg?: string;
};

/**
 * @description Usuário ou endereço não encontrado
 */
export type PutActiveAddress404 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description ID do endereço não fornecido
 */
export type PutActiveAddress422 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type PutActiveAddress500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description ID do endereço que será definido como principal
 */
export type PutActiveAddressMutationRequest = {
  /**
   * @type string | undefined
   */
  type?: string;
  /**
   * @type array | undefined
   */
  required?: string[];
  /**
   * @type object | undefined
   */
  properties?: {
    /**
     * @type object | undefined
     */
    addressId?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
  };
};

export type PutActiveAddressMutationResponse = PutActiveAddress200;

export type PutActiveAddressMutation = {
  Response: PutActiveAddress200;
  Request: PutActiveAddressMutationRequest;
  Errors: PutActiveAddress404 | PutActiveAddress422 | PutActiveAddress500;
};
