/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutAddressHeaderParams = {
  /**
   * @type string | undefined
   */
  authorization?: string;
};

/**
 * @description Endereço atualizado com sucesso
 */
export type PutAddress200 = {
  /**
   * @type string | undefined
   */
  msg?: string;
};

/**
 * @description Endereço está idêntico ao banco de dados (nenhuma modificação realizada)
 */
export type PutAddress304 = {
  /**
   * @type string | undefined
   */
  msg?: string;
};

/**
 * @description Não autorizado
 */
export type PutAddress401 = any;

/**
 * @description Acesso Negado
 */
export type PutAddress403 = any;

/**
 * @description Parâmetros obrigatórios ausentes ou inválidos no body
 */
export type PutAddress422 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type PutAddress500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

export const putAddressMutationRequestTypeEnum = {
  Casa: "Casa",
  Trabalho: "Trabalho",
  Outros: "Outros",
} as const;

export type PutAddressMutationRequestTypeEnumKey =
  (typeof putAddressMutationRequestTypeEnum)[keyof typeof putAddressMutationRequestTypeEnum];

/**
 * @description Dados do endereço a ser atualizado
 */
export type PutAddressMutationRequest = {
  /**
   * @description ID do endereço a ser atualizado
   * @type string
   */
  addressId: string;
  /**
   * @description CEP do endereço
   * @type string
   */
  cep: string;
  /**
   * @description Apelido opcional do endereço
   * @type string | undefined
   */
  name?: string;
  /**
   * @description Logradouro
   * @type string
   */
  endereco: string;
  /**
   * @description Bairro
   * @type string
   */
  bairro: string;
  /**
   * @description Número do imóvel (opcional)
   * @type string | undefined
   */
  numero?: string;
  /**
   * @description Cidade
   * @type string
   */
  cidade: string;
  /**
   * @description Estado
   * @type string
   */
  estado: string;
  /**
   * @description Complemento do endereço (opcional)
   * @type string | undefined
   */
  complemento?: string;
  /**
   * @description Categoria do endereço
   * @type string | undefined
   */
  type?: PutAddressMutationRequestTypeEnumKey;
  /**
   * @description Indica se é o endereço ativo
   * @type boolean | undefined
   */
  active?: boolean;
};

export type PutAddressMutationResponse = PutAddress200;

export type PutAddressMutation = {
  Response: PutAddress200;
  Request: PutAddressMutationRequest;
  HeaderParams: PutAddressHeaderParams;
  Errors: PutAddress401 | PutAddress403 | PutAddress422 | PutAddress500;
};
