/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Endereço atualizado com sucesso
 */
export type PutAddress200 = {
  /**
   * @type string | undefined
   */
  msg?: string;
};

/**
 * @description Endereço está idêntico ao banco de dados (nenhuma modificação realizada)
 */
export type PutAddress304 = {
  /**
   * @type string | undefined
   */
  msg?: string;
};

/**
 * @description Parâmetros obrigatórios não enviados no body
 */
export type PutAddress422 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Erro interno no servidor
 */
export type PutAddress500 = {
  /**
   * @type string | undefined
   */
  error?: string;
};

/**
 * @description Dados do endereço a ser atualizado
 */
export type PutAddressMutationRequest = {
  /**
   * @type string | undefined
   */
  type?: string;
  /**
   * @type array | undefined
   */
  required?: string[];
  /**
   * @type object | undefined
   */
  properties?: {
    /**
     * @type object | undefined
     */
    addressId?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
    /**
     * @type object | undefined
     */
    cep?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
    /**
     * @type object | undefined
     */
    name?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
    /**
     * @type object | undefined
     */
    endereco?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
    /**
     * @type object | undefined
     */
    bairro?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
    /**
     * @type object | undefined
     */
    estado?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
    /**
     * @type object | undefined
     */
    complemento?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
      /**
       * @type string | undefined
       */
      description?: string;
    };
    /**
     * @type object | undefined
     */
    active?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type boolean | undefined
       */
      example?: boolean;
      /**
       * @type string | undefined
       */
      description?: string;
    };
  };
};

export type PutAddressMutationResponse = PutAddress200;

export type PutAddressMutation = {
  Response: PutAddress200;
  Request: PutAddressMutationRequest;
  Errors: PutAddress422 | PutAddress500;
};
