/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type WebhookMessageCreated = {
  /**
   * @type string | undefined
   */
  type?: string;
  /**
   * @type object | undefined
   */
  properties?: {
    /**
     * @type object | undefined
     */
    eventId?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
    /**
     * @type object | undefined
     */
    type?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
    /**
     * @type object | undefined
     */
    occurredAt?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type string | undefined
       */
      format?: string;
      /**
       * @type string | undefined
       */
      example?: string;
    };
    /**
     * @type object | undefined
     */
    data?: {
      /**
       * @type string | undefined
       */
      type?: string;
      /**
       * @type object | undefined
       */
      properties?: {
        /**
         * @type object | undefined
         */
        messageId?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        conversation?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        sender?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        senderName?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        content?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
        /**
         * @type object | undefined
         */
        createdAt?: {
          /**
           * @type string | undefined
           */
          type?: string;
          /**
           * @type string | undefined
           */
          format?: string;
          /**
           * @type string | undefined
           */
          example?: string;
        };
      };
    };
  };
};
