/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type WebhookMessageCreated = {
  /**
   * @type string | undefined
   */
  eventId?: string;
  /**
   * @type string | undefined
   */
  type?: string;
  /**
   * @type string | undefined, date-time
   */
  occurredAt?: string;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    messageId?: string;
    /**
     * @type string | undefined
     */
    conversation?: string;
    /**
     * @type string | undefined
     */
    sender?: string;
    /**
     * @type string | undefined
     */
    senderName?: string;
    /**
     * @type string | undefined
     */
    content?: string;
    /**
     * @type string | undefined, date-time
     */
    createdAt?: string;
  };
};
