/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  DeleteCleanupMutationResponse,
  DeleteCleanup403,
  DeleteCleanup500,
} from "../types/DeleteCleanup.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteCleanupMutationKey = () => [{ url: "/cleanup" }] as const;

export type DeleteCleanupMutationKey = ReturnType<
  typeof deleteCleanupMutationKey
>;

/**
 * @description Remove todos os documentos das coleções. **Disponível apenas em dev/teste.**
 * @summary Limpar dados de teste
 * {@link /cleanup}
 */
export async function deleteCleanup(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteCleanupMutationResponse,
    ResponseErrorConfig<DeleteCleanup403 | DeleteCleanup500>,
    unknown
  >({ method: "DELETE", url: `/cleanup`, ...requestConfig });
  return res.data;
}

export function deleteCleanupMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteCleanupMutationKey();
  return mutationOptions<
    DeleteCleanupMutationResponse,
    ResponseErrorConfig<DeleteCleanup403 | DeleteCleanup500>,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return deleteCleanup(config);
    },
  });
}

/**
 * @description Remove todos os documentos das coleções. **Disponível apenas em dev/teste.**
 * @summary Limpar dados de teste
 * {@link /cleanup}
 */
export function useDeleteCleanup<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteCleanupMutationResponse,
      ResponseErrorConfig<DeleteCleanup403 | DeleteCleanup500>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteCleanupMutationKey();

  const baseOptions = deleteCleanupMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteCleanupMutationResponse,
    ResponseErrorConfig<DeleteCleanup403 | DeleteCleanup500>,
    void,
    TContext
  >;

  return useMutation<
    DeleteCleanupMutationResponse,
    ResponseErrorConfig<DeleteCleanup403 | DeleteCleanup500>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteCleanupMutationResponse,
    ResponseErrorConfig<DeleteCleanup403 | DeleteCleanup500>,
    void,
    TContext
  >;
}
