/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetSearchProfessionalIdQueryResponse,
  GetSearchProfessionalIdPathParams,
  GetSearchProfessionalId400,
  GetSearchProfessionalId404,
  GetSearchProfessionalId500,
} from "../types/GetSearchProfessionalId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getSearchProfessionalIdSuspenseQueryKey = (
  id: GetSearchProfessionalIdPathParams["id"],
) => [{ url: "/search/professional/:id", params: { id: id } }] as const;

export type GetSearchProfessionalIdSuspenseQueryKey = ReturnType<
  typeof getSearchProfessionalIdSuspenseQueryKey
>;

/**
 * @description Retorna os dados públicos de um profissional específico.
 * @summary Busca detalhes de um profissional por ID
 * {@link /search/professional/:id}
 */
export async function getSearchProfessionalIdSuspense(
  id: GetSearchProfessionalIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetSearchProfessionalIdQueryResponse,
    ResponseErrorConfig<
      | GetSearchProfessionalId400
      | GetSearchProfessionalId404
      | GetSearchProfessionalId500
    >,
    unknown
  >({ method: "GET", url: `/search/professional/${id}`, ...requestConfig });
  return res.data;
}

export function getSearchProfessionalIdSuspenseQueryOptions(
  id: GetSearchProfessionalIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getSearchProfessionalIdSuspenseQueryKey(id);
  return queryOptions<
    GetSearchProfessionalIdQueryResponse,
    ResponseErrorConfig<
      | GetSearchProfessionalId400
      | GetSearchProfessionalId404
      | GetSearchProfessionalId500
    >,
    GetSearchProfessionalIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getSearchProfessionalIdSuspense(id, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna os dados públicos de um profissional específico.
 * @summary Busca detalhes de um profissional por ID
 * {@link /search/professional/:id}
 */
export function useGetSearchProfessionalIdSuspense<
  TData = GetSearchProfessionalIdQueryResponse,
  TQueryKey extends QueryKey = GetSearchProfessionalIdSuspenseQueryKey,
>(
  id: GetSearchProfessionalIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetSearchProfessionalIdQueryResponse,
        ResponseErrorConfig<
          | GetSearchProfessionalId400
          | GetSearchProfessionalId404
          | GetSearchProfessionalId500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getSearchProfessionalIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getSearchProfessionalIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetSearchProfessionalId400
      | GetSearchProfessionalId404
      | GetSearchProfessionalId500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
