/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetUserQueryResponse,
  GetUserHeaderParams,
  GetUser401,
  GetUser403,
  GetUser404,
  GetUser500,
} from "../types/GetUser.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getUserSuspenseQueryKey = () => [{ url: "/user" }] as const;

export type GetUserSuspenseQueryKey = ReturnType<
  typeof getUserSuspenseQueryKey
>;

/**
 * @description Endpoint protegido que retorna todos os dados do usuário autenticado, exceto campos sensíveis (hashedOTP, __v). Retorna a URL da imagem de perfil armazenada no Cloudinary, quando existir.
 * @summary Retorna todas as informações do usuário logado
 * {@link /user}
 */
export async function getUserSuspense(
  headers: GetUserHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetUserQueryResponse,
    ResponseErrorConfig<GetUser401 | GetUser403 | GetUser404 | GetUser500>,
    unknown
  >({
    method: "GET",
    url: `/user`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getUserSuspenseQueryOptions(
  headers: GetUserHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getUserSuspenseQueryKey();
  return queryOptions<
    GetUserQueryResponse,
    ResponseErrorConfig<GetUser401 | GetUser403 | GetUser404 | GetUser500>,
    GetUserQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getUserSuspense(headers, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Endpoint protegido que retorna todos os dados do usuário autenticado, exceto campos sensíveis (hashedOTP, __v). Retorna a URL da imagem de perfil armazenada no Cloudinary, quando existir.
 * @summary Retorna todas as informações do usuário logado
 * {@link /user}
 */
export function useGetUserSuspense<
  TData = GetUserQueryResponse,
  TQueryKey extends QueryKey = GetUserSuspenseQueryKey,
>(
  headers: GetUserHeaderParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetUserQueryResponse,
        ResponseErrorConfig<GetUser401 | GetUser403 | GetUser404 | GetUser500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getUserSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getUserSuspenseQueryOptions(headers, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetUser401 | GetUser403 | GetUser404 | GetUser500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
