/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetAppointmentsMeQueryResponse,
  GetAppointmentsMeQueryParams,
  GetAppointmentsMeHeaderParams,
  GetAppointmentsMe401,
  GetAppointmentsMe403,
  GetAppointmentsMe500,
} from "../types/GetAppointmentsMe.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getAppointmentsMeSuspenseQueryKey = (
  params?: GetAppointmentsMeQueryParams,
) => [{ url: "/appointments/me" }, ...(params ? [params] : [])] as const;

export type GetAppointmentsMeSuspenseQueryKey = ReturnType<
  typeof getAppointmentsMeSuspenseQueryKey
>;

/**
 * @description Lista agendamentos do usuário autenticado (paciente ou profissional). Suporta paginação, filtros de status e intervalo de datas.
 * @summary Meus agendamentos (Paciente ou Profissional)
 * {@link /appointments/me}
 */
export async function getAppointmentsMeSuspense(
  headers: GetAppointmentsMeHeaderParams,
  params?: GetAppointmentsMeQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAppointmentsMeQueryResponse,
    ResponseErrorConfig<
      GetAppointmentsMe401 | GetAppointmentsMe403 | GetAppointmentsMe500
    >,
    unknown
  >({
    method: "GET",
    url: `/appointments/me`,
    params,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getAppointmentsMeSuspenseQueryOptions(
  headers: GetAppointmentsMeHeaderParams,
  params?: GetAppointmentsMeQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getAppointmentsMeSuspenseQueryKey(params);
  return queryOptions<
    GetAppointmentsMeQueryResponse,
    ResponseErrorConfig<
      GetAppointmentsMe401 | GetAppointmentsMe403 | GetAppointmentsMe500
    >,
    GetAppointmentsMeQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getAppointmentsMeSuspense(headers, params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Lista agendamentos do usuário autenticado (paciente ou profissional). Suporta paginação, filtros de status e intervalo de datas.
 * @summary Meus agendamentos (Paciente ou Profissional)
 * {@link /appointments/me}
 */
export function useGetAppointmentsMeSuspense<
  TData = GetAppointmentsMeQueryResponse,
  TQueryKey extends QueryKey = GetAppointmentsMeSuspenseQueryKey,
>(
  headers: GetAppointmentsMeHeaderParams,
  params?: GetAppointmentsMeQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetAppointmentsMeQueryResponse,
        ResponseErrorConfig<
          GetAppointmentsMe401 | GetAppointmentsMe403 | GetAppointmentsMe500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getAppointmentsMeSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getAppointmentsMeSuspenseQueryOptions(headers, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      GetAppointmentsMe401 | GetAppointmentsMe403 | GetAppointmentsMe500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
