/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetMessagesContactsQueryResponse,
  GetMessagesContactsHeaderParams,
  GetMessagesContacts401,
  GetMessagesContacts403,
  GetMessagesContacts500,
} from "../types/GetMessagesContacts.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMessagesContactsQueryKey = () =>
  [{ url: "/messages/contacts" }] as const;

export type GetMessagesContactsQueryKey = ReturnType<
  typeof getMessagesContactsQueryKey
>;

/**
 * @description Lista todos os contatos (pacientes ou profissionais) do usuário autenticado, incluindo último envio e quantidade de mensagens não lidas.
 * @summary Listar contatos do usuário
 * {@link /messages/contacts}
 */
export async function getMessagesContacts(
  headers: GetMessagesContactsHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetMessagesContactsQueryResponse,
    ResponseErrorConfig<
      GetMessagesContacts401 | GetMessagesContacts403 | GetMessagesContacts500
    >,
    unknown
  >({
    method: "GET",
    url: `/messages/contacts`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getMessagesContactsQueryOptions(
  headers: GetMessagesContactsHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getMessagesContactsQueryKey();
  return queryOptions<
    GetMessagesContactsQueryResponse,
    ResponseErrorConfig<
      GetMessagesContacts401 | GetMessagesContacts403 | GetMessagesContacts500
    >,
    GetMessagesContactsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getMessagesContacts(headers, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Lista todos os contatos (pacientes ou profissionais) do usuário autenticado, incluindo último envio e quantidade de mensagens não lidas.
 * @summary Listar contatos do usuário
 * {@link /messages/contacts}
 */
export function useGetMessagesContacts<
  TData = GetMessagesContactsQueryResponse,
  TQueryData = GetMessagesContactsQueryResponse,
  TQueryKey extends QueryKey = GetMessagesContactsQueryKey,
>(
  headers: GetMessagesContactsHeaderParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetMessagesContactsQueryResponse,
        ResponseErrorConfig<
          | GetMessagesContacts401
          | GetMessagesContacts403
          | GetMessagesContacts500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getMessagesContactsQueryKey();

  const query = useQuery(
    {
      ...getMessagesContactsQueryOptions(headers, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      GetMessagesContacts401 | GetMessagesContacts403 | GetMessagesContacts500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
