/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetAddressQueryResponse,
  GetAddress401,
  GetAddress404,
  GetAddress500,
} from "../types/GetAddress.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getAddressSuspenseQueryKey = () => [{ url: "/address" }] as const;

export type GetAddressSuspenseQueryKey = ReturnType<
  typeof getAddressSuspenseQueryKey
>;

/**
 * @description Endpoint protegido que retorna todos os endereços cadastrados do usuário logado.
 * @summary Retorna todos os endereços do usuário
 * {@link /address}
 */
export async function getAddressSuspense(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAddressQueryResponse,
    ResponseErrorConfig<GetAddress401 | GetAddress404 | GetAddress500>,
    unknown
  >({ method: "GET", url: `/address`, ...requestConfig });
  return res.data;
}

export function getAddressSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getAddressSuspenseQueryKey();
  return queryOptions<
    GetAddressQueryResponse,
    ResponseErrorConfig<GetAddress401 | GetAddress404 | GetAddress500>,
    GetAddressQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getAddressSuspense({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @description Endpoint protegido que retorna todos os endereços cadastrados do usuário logado.
 * @summary Retorna todos os endereços do usuário
 * {@link /address}
 */
export function useGetAddressSuspense<
  TData = GetAddressQueryResponse,
  TQueryKey extends QueryKey = GetAddressSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetAddressQueryResponse,
        ResponseErrorConfig<GetAddress401 | GetAddress404 | GetAddress500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getAddressSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getAddressSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetAddress401 | GetAddress404 | GetAddress500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
