/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetSpecialtiesQueryResponse,
  GetSpecialties500,
} from "../types/GetSpecialties.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getSpecialtiesSuspenseQueryKey = () =>
  [{ url: "/specialties" }] as const;

export type GetSpecialtiesSuspenseQueryKey = ReturnType<
  typeof getSpecialtiesSuspenseQueryKey
>;

/**
 * @description Retorna a lista canônica de especialidades disponíveis no sistema. Essa lista é utilizada como fonte única (single source of truth) para cadastro e filtros.
 * @summary Lista todas as especialidades
 * {@link /specialties}
 */
export async function getSpecialtiesSuspense(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetSpecialtiesQueryResponse,
    ResponseErrorConfig<GetSpecialties500>,
    unknown
  >({ method: "GET", url: `/specialties`, ...requestConfig });
  return res.data;
}

export function getSpecialtiesSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getSpecialtiesSuspenseQueryKey();
  return queryOptions<
    GetSpecialtiesQueryResponse,
    ResponseErrorConfig<GetSpecialties500>,
    GetSpecialtiesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getSpecialtiesSuspense({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna a lista canônica de especialidades disponíveis no sistema. Essa lista é utilizada como fonte única (single source of truth) para cadastro e filtros.
 * @summary Lista todas as especialidades
 * {@link /specialties}
 */
export function useGetSpecialtiesSuspense<
  TData = GetSpecialtiesQueryResponse,
  TQueryKey extends QueryKey = GetSpecialtiesSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetSpecialtiesQueryResponse,
        ResponseErrorConfig<GetSpecialties500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getSpecialtiesSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getSpecialtiesSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetSpecialties500>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
