/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetAppointmentsIdQueryResponse,
  GetAppointmentsIdPathParams,
  GetAppointmentsIdHeaderParams,
  GetAppointmentsId400,
  GetAppointmentsId401,
  GetAppointmentsId403,
  GetAppointmentsId404,
  GetAppointmentsId500,
} from "../types/GetAppointmentsId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getAppointmentsIdSuspenseQueryKey = (
  id: GetAppointmentsIdPathParams["id"],
) => [{ url: "/appointments/:id", params: { id: id } }] as const;

export type GetAppointmentsIdSuspenseQueryKey = ReturnType<
  typeof getAppointmentsIdSuspenseQueryKey
>;

/**
 * @description Retorna informações detalhadas de um agendamento específico. O agendamento não pode estar cancelado.
 * @summary Buscar detalhes de um agendamento
 * {@link /appointments/:id}
 */
export async function getAppointmentsIdSuspense(
  id: GetAppointmentsIdPathParams["id"],
  headers: GetAppointmentsIdHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAppointmentsIdQueryResponse,
    ResponseErrorConfig<
      | GetAppointmentsId400
      | GetAppointmentsId401
      | GetAppointmentsId403
      | GetAppointmentsId404
      | GetAppointmentsId500
    >,
    unknown
  >({
    method: "GET",
    url: `/appointments/${id}`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getAppointmentsIdSuspenseQueryOptions(
  id: GetAppointmentsIdPathParams["id"],
  headers: GetAppointmentsIdHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getAppointmentsIdSuspenseQueryKey(id);
  return queryOptions<
    GetAppointmentsIdQueryResponse,
    ResponseErrorConfig<
      | GetAppointmentsId400
      | GetAppointmentsId401
      | GetAppointmentsId403
      | GetAppointmentsId404
      | GetAppointmentsId500
    >,
    GetAppointmentsIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getAppointmentsIdSuspense(id, headers, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna informações detalhadas de um agendamento específico. O agendamento não pode estar cancelado.
 * @summary Buscar detalhes de um agendamento
 * {@link /appointments/:id}
 */
export function useGetAppointmentsIdSuspense<
  TData = GetAppointmentsIdQueryResponse,
  TQueryKey extends QueryKey = GetAppointmentsIdSuspenseQueryKey,
>(
  id: GetAppointmentsIdPathParams["id"],
  headers: GetAppointmentsIdHeaderParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetAppointmentsIdQueryResponse,
        ResponseErrorConfig<
          | GetAppointmentsId400
          | GetAppointmentsId401
          | GetAppointmentsId403
          | GetAppointmentsId404
          | GetAppointmentsId500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getAppointmentsIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getAppointmentsIdSuspenseQueryOptions(id, headers, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetAppointmentsId400
      | GetAppointmentsId401
      | GetAppointmentsId403
      | GetAppointmentsId404
      | GetAppointmentsId500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
