/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetSearchProfessionalsQueryResponse,
  GetSearchProfessionalsQueryParams,
  GetSearchProfessionals500,
} from "../types/GetSearchProfessionals.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getSearchProfessionalsQueryKey = (
  params?: GetSearchProfessionalsQueryParams,
) => [{ url: "/search/professionals" }, ...(params ? [params] : [])] as const;

export type GetSearchProfessionalsQueryKey = ReturnType<
  typeof getSearchProfessionalsQueryKey
>;

/**
 * @description Retorna profissionais com filtros opcionais de especialidade, acessibilidade e tipo de serviço. Os filtros podem ser combinados (AND).
 * @summary Lista profissionais com filtros combinados
 * {@link /search/professionals}
 */
export async function getSearchProfessionals(
  params?: GetSearchProfessionalsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetSearchProfessionalsQueryResponse,
    ResponseErrorConfig<GetSearchProfessionals500>,
    unknown
  >({ method: "GET", url: `/search/professionals`, params, ...requestConfig });
  return res.data;
}

export function getSearchProfessionalsQueryOptions(
  params?: GetSearchProfessionalsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getSearchProfessionalsQueryKey(params);
  return queryOptions<
    GetSearchProfessionalsQueryResponse,
    ResponseErrorConfig<GetSearchProfessionals500>,
    GetSearchProfessionalsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getSearchProfessionals(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna profissionais com filtros opcionais de especialidade, acessibilidade e tipo de serviço. Os filtros podem ser combinados (AND).
 * @summary Lista profissionais com filtros combinados
 * {@link /search/professionals}
 */
export function useGetSearchProfessionals<
  TData = GetSearchProfessionalsQueryResponse,
  TQueryData = GetSearchProfessionalsQueryResponse,
  TQueryKey extends QueryKey = GetSearchProfessionalsQueryKey,
>(
  params?: GetSearchProfessionalsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetSearchProfessionalsQueryResponse,
        ResponseErrorConfig<GetSearchProfessionals500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getSearchProfessionalsQueryKey(params);

  const query = useQuery(
    {
      ...getSearchProfessionalsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetSearchProfessionals500>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
