/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetAddressQueryResponse,
  GetAddressHeaderParams,
  GetAddress401,
  GetAddress403,
  GetAddress404,
  GetAddress500,
} from "../types/GetAddress.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAddressQueryKey = () => [{ url: "/address" }] as const;

export type GetAddressQueryKey = ReturnType<typeof getAddressQueryKey>;

/**
 * @description Endpoint protegido que retorna todos os endereços cadastrados do usuário logado.
 * @summary Retorna todos os endereços do usuário
 * {@link /address}
 */
export async function getAddress(
  headers?: GetAddressHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAddressQueryResponse,
    ResponseErrorConfig<
      GetAddress401 | GetAddress403 | GetAddress404 | GetAddress500
    >,
    unknown
  >({
    method: "GET",
    url: `/address`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getAddressQueryOptions(
  headers?: GetAddressHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getAddressQueryKey();
  return queryOptions<
    GetAddressQueryResponse,
    ResponseErrorConfig<
      GetAddress401 | GetAddress403 | GetAddress404 | GetAddress500
    >,
    GetAddressQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getAddress(headers, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Endpoint protegido que retorna todos os endereços cadastrados do usuário logado.
 * @summary Retorna todos os endereços do usuário
 * {@link /address}
 */
export function useGetAddress<
  TData = GetAddressQueryResponse,
  TQueryData = GetAddressQueryResponse,
  TQueryKey extends QueryKey = GetAddressQueryKey,
>(
  headers?: GetAddressHeaderParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetAddressQueryResponse,
        ResponseErrorConfig<
          GetAddress401 | GetAddress403 | GetAddress404 | GetAddress500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getAddressQueryKey();

  const query = useQuery(
    {
      ...getAddressQueryOptions(headers, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      GetAddress401 | GetAddress403 | GetAddress404 | GetAddress500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
