/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetSearchProfessionalbyspecialitySpecialityQueryResponse,
  GetSearchProfessionalbyspecialitySpecialityPathParams,
  GetSearchProfessionalbyspecialitySpeciality400,
  GetSearchProfessionalbyspecialitySpeciality500,
} from "../types/GetSearchProfessionalbyspecialitySpeciality.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getSearchProfessionalbyspecialitySpecialityQueryKey = (
  speciality: GetSearchProfessionalbyspecialitySpecialityPathParams["speciality"],
  page: GetSearchProfessionalbyspecialitySpecialityPathParams["page"],
) =>
  [
    {
      url: "/search/professionalBySpeciality/:speciality",
      params: { speciality: speciality },
    },
  ] as const;

export type GetSearchProfessionalbyspecialitySpecialityQueryKey = ReturnType<
  typeof getSearchProfessionalbyspecialitySpecialityQueryKey
>;

/**
 * @description Retorna uma lista paginada de até 10 profissionais de uma especialidade específica. A especialidade deve ser informada como parâmetro de rota.
 * @summary Pesquisa profissionais por especialidade
 * {@link /search/professionalBySpeciality/:speciality}
 */
export async function getSearchProfessionalbyspecialitySpeciality(
  speciality: GetSearchProfessionalbyspecialitySpecialityPathParams["speciality"],
  page: GetSearchProfessionalbyspecialitySpecialityPathParams["page"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetSearchProfessionalbyspecialitySpecialityQueryResponse,
    ResponseErrorConfig<
      | GetSearchProfessionalbyspecialitySpeciality400
      | GetSearchProfessionalbyspecialitySpeciality500
    >,
    unknown
  >({
    method: "GET",
    url: `/search/professionalBySpeciality/${speciality}`,
    ...requestConfig,
  });
  return res.data;
}

export function getSearchProfessionalbyspecialitySpecialityQueryOptions(
  speciality: GetSearchProfessionalbyspecialitySpecialityPathParams["speciality"],
  page: GetSearchProfessionalbyspecialitySpecialityPathParams["page"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getSearchProfessionalbyspecialitySpecialityQueryKey(
    speciality,
    page,
  );
  return queryOptions<
    GetSearchProfessionalbyspecialitySpecialityQueryResponse,
    ResponseErrorConfig<
      | GetSearchProfessionalbyspecialitySpeciality400
      | GetSearchProfessionalbyspecialitySpeciality500
    >,
    GetSearchProfessionalbyspecialitySpecialityQueryResponse,
    typeof queryKey
  >({
    enabled: !!(speciality && page),
    queryKey,
    queryFn: async ({ signal }) => {
      return getSearchProfessionalbyspecialitySpeciality(speciality, page, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna uma lista paginada de até 10 profissionais de uma especialidade específica. A especialidade deve ser informada como parâmetro de rota.
 * @summary Pesquisa profissionais por especialidade
 * {@link /search/professionalBySpeciality/:speciality}
 */
export function useGetSearchProfessionalbyspecialitySpeciality<
  TData = GetSearchProfessionalbyspecialitySpecialityQueryResponse,
  TQueryData = GetSearchProfessionalbyspecialitySpecialityQueryResponse,
  TQueryKey extends QueryKey =
    GetSearchProfessionalbyspecialitySpecialityQueryKey,
>(
  speciality: GetSearchProfessionalbyspecialitySpecialityPathParams["speciality"],
  page: GetSearchProfessionalbyspecialitySpecialityPathParams["page"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetSearchProfessionalbyspecialitySpecialityQueryResponse,
        ResponseErrorConfig<
          | GetSearchProfessionalbyspecialitySpeciality400
          | GetSearchProfessionalbyspecialitySpeciality500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getSearchProfessionalbyspecialitySpecialityQueryKey(speciality, page);

  const query = useQuery(
    {
      ...getSearchProfessionalbyspecialitySpecialityQueryOptions(
        speciality,
        page,
        config,
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetSearchProfessionalbyspecialitySpeciality400
      | GetSearchProfessionalbyspecialitySpeciality500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
