/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetAppointmentsIdQueryResponse,
  GetAppointmentsIdPathParams,
  GetAppointmentsIdHeaderParams,
  GetAppointmentsId400,
  GetAppointmentsId401,
  GetAppointmentsId403,
  GetAppointmentsId404,
  GetAppointmentsId500,
} from "../types/GetAppointmentsId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAppointmentsIdQueryKey = (
  id: GetAppointmentsIdPathParams["id"],
) => [{ url: "/appointments/:id", params: { id: id } }] as const;

export type GetAppointmentsIdQueryKey = ReturnType<
  typeof getAppointmentsIdQueryKey
>;

/**
 * @description Retorna informações detalhadas de um agendamento específico. O agendamento não pode estar cancelado.
 * @summary Buscar detalhes de um agendamento
 * {@link /appointments/:id}
 */
export async function getAppointmentsId(
  id: GetAppointmentsIdPathParams["id"],
  headers: GetAppointmentsIdHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAppointmentsIdQueryResponse,
    ResponseErrorConfig<
      | GetAppointmentsId400
      | GetAppointmentsId401
      | GetAppointmentsId403
      | GetAppointmentsId404
      | GetAppointmentsId500
    >,
    unknown
  >({
    method: "GET",
    url: `/appointments/${id}`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getAppointmentsIdQueryOptions(
  id: GetAppointmentsIdPathParams["id"],
  headers: GetAppointmentsIdHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getAppointmentsIdQueryKey(id);
  return queryOptions<
    GetAppointmentsIdQueryResponse,
    ResponseErrorConfig<
      | GetAppointmentsId400
      | GetAppointmentsId401
      | GetAppointmentsId403
      | GetAppointmentsId404
      | GetAppointmentsId500
    >,
    GetAppointmentsIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getAppointmentsId(id, headers, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna informações detalhadas de um agendamento específico. O agendamento não pode estar cancelado.
 * @summary Buscar detalhes de um agendamento
 * {@link /appointments/:id}
 */
export function useGetAppointmentsId<
  TData = GetAppointmentsIdQueryResponse,
  TQueryData = GetAppointmentsIdQueryResponse,
  TQueryKey extends QueryKey = GetAppointmentsIdQueryKey,
>(
  id: GetAppointmentsIdPathParams["id"],
  headers: GetAppointmentsIdHeaderParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetAppointmentsIdQueryResponse,
        ResponseErrorConfig<
          | GetAppointmentsId400
          | GetAppointmentsId401
          | GetAppointmentsId403
          | GetAppointmentsId404
          | GetAppointmentsId500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getAppointmentsIdQueryKey(id);

  const query = useQuery(
    {
      ...getAppointmentsIdQueryOptions(id, headers, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetAppointmentsId400
      | GetAppointmentsId401
      | GetAppointmentsId403
      | GetAppointmentsId404
      | GetAppointmentsId500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
