/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type { GetTesteQueryResponse } from "../types/GetTeste.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getTesteSuspenseQueryKey = () => [{ url: "/teste" }] as const;

export type GetTesteSuspenseQueryKey = ReturnType<
  typeof getTesteSuspenseQueryKey
>;

/**
 * @summary Teste para verificar se API está funcionando
 * {@link /teste}
 */
export async function getTesteSuspense(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTesteQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/teste`, ...requestConfig });
  return res.data;
}

export function getTesteSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getTesteSuspenseQueryKey();
  return queryOptions<
    GetTesteQueryResponse,
    ResponseErrorConfig<Error>,
    GetTesteQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getTesteSuspense({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Teste para verificar se API está funcionando
 * {@link /teste}
 */
export function useGetTesteSuspense<
  TData = GetTesteQueryResponse,
  TQueryKey extends QueryKey = GetTesteSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetTesteQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getTesteSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getTesteSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
