/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetSearchProfessionalbyspecialitySpecialityQueryResponse,
  GetSearchProfessionalbyspecialitySpecialityPathParams,
  GetSearchProfessionalbyspecialitySpeciality400,
  GetSearchProfessionalbyspecialitySpeciality500,
} from "../types/GetSearchProfessionalbyspecialitySpeciality.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getSearchProfessionalbyspecialitySpecialitySuspenseQueryKey = (
  speciality: GetSearchProfessionalbyspecialitySpecialityPathParams["speciality"],
  page: GetSearchProfessionalbyspecialitySpecialityPathParams["page"],
) =>
  [
    {
      url: "/search/professionalBySpeciality/:speciality",
      params: { speciality: speciality },
    },
  ] as const;

export type GetSearchProfessionalbyspecialitySpecialitySuspenseQueryKey =
  ReturnType<
    typeof getSearchProfessionalbyspecialitySpecialitySuspenseQueryKey
  >;

/**
 * @description Retorna uma lista paginada de até 10 profissionais de uma especialidade específica. A especialidade deve ser informada como parâmetro de rota.
 * @summary Pesquisa profissionais por especialidade
 * {@link /search/professionalBySpeciality/:speciality}
 */
export async function getSearchProfessionalbyspecialitySpecialitySuspense(
  speciality: GetSearchProfessionalbyspecialitySpecialityPathParams["speciality"],
  page: GetSearchProfessionalbyspecialitySpecialityPathParams["page"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetSearchProfessionalbyspecialitySpecialityQueryResponse,
    ResponseErrorConfig<
      | GetSearchProfessionalbyspecialitySpeciality400
      | GetSearchProfessionalbyspecialitySpeciality500
    >,
    unknown
  >({
    method: "GET",
    url: `/search/professionalBySpeciality/${speciality}`,
    ...requestConfig,
  });
  return res.data;
}

export function getSearchProfessionalbyspecialitySpecialitySuspenseQueryOptions(
  speciality: GetSearchProfessionalbyspecialitySpecialityPathParams["speciality"],
  page: GetSearchProfessionalbyspecialitySpecialityPathParams["page"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getSearchProfessionalbyspecialitySpecialitySuspenseQueryKey(
    speciality,
    page,
  );
  return queryOptions<
    GetSearchProfessionalbyspecialitySpecialityQueryResponse,
    ResponseErrorConfig<
      | GetSearchProfessionalbyspecialitySpeciality400
      | GetSearchProfessionalbyspecialitySpeciality500
    >,
    GetSearchProfessionalbyspecialitySpecialityQueryResponse,
    typeof queryKey
  >({
    enabled: !!(speciality && page),
    queryKey,
    queryFn: async ({ signal }) => {
      return getSearchProfessionalbyspecialitySpecialitySuspense(
        speciality,
        page,
        { ...config, signal: config.signal ?? signal },
      );
    },
  });
}

/**
 * @description Retorna uma lista paginada de até 10 profissionais de uma especialidade específica. A especialidade deve ser informada como parâmetro de rota.
 * @summary Pesquisa profissionais por especialidade
 * {@link /search/professionalBySpeciality/:speciality}
 */
export function useGetSearchProfessionalbyspecialitySpecialitySuspense<
  TData = GetSearchProfessionalbyspecialitySpecialityQueryResponse,
  TQueryKey extends QueryKey =
    GetSearchProfessionalbyspecialitySpecialitySuspenseQueryKey,
>(
  speciality: GetSearchProfessionalbyspecialitySpecialityPathParams["speciality"],
  page: GetSearchProfessionalbyspecialitySpecialityPathParams["page"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetSearchProfessionalbyspecialitySpecialityQueryResponse,
        ResponseErrorConfig<
          | GetSearchProfessionalbyspecialitySpeciality400
          | GetSearchProfessionalbyspecialitySpeciality500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getSearchProfessionalbyspecialitySpecialitySuspenseQueryKey(
      speciality,
      page,
    );

  const query = useSuspenseQuery(
    {
      ...getSearchProfessionalbyspecialitySpecialitySuspenseQueryOptions(
        speciality,
        page,
        config,
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetSearchProfessionalbyspecialitySpeciality400
      | GetSearchProfessionalbyspecialitySpeciality500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
