/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetSearchHighlightsweekQueryResponse,
  GetSearchHighlightsweekQueryParams,
  GetSearchHighlightsweek400,
  GetSearchHighlightsweek500,
} from "../types/GetSearchHighlightsweek.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getSearchHighlightsweekQueryKey = (
  params?: GetSearchHighlightsweekQueryParams,
) => [{ url: "/search/highlightsWeek" }, ...(params ? [params] : [])] as const;

export type GetSearchHighlightsweekQueryKey = ReturnType<
  typeof getSearchHighlightsweekQueryKey
>;

/**
 * @description Retorna uma lista paginada de até 10 profissionais que são destaques da semana. A paginação é controlada pelo query param `page`.
 * @summary Pesquisa os profissionais destaques da semana
 * {@link /search/highlightsWeek}
 */
export async function getSearchHighlightsweek(
  params?: GetSearchHighlightsweekQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetSearchHighlightsweekQueryResponse,
    ResponseErrorConfig<
      GetSearchHighlightsweek400 | GetSearchHighlightsweek500
    >,
    unknown
  >({ method: "GET", url: `/search/highlightsWeek`, params, ...requestConfig });
  return res.data;
}

export function getSearchHighlightsweekQueryOptions(
  params?: GetSearchHighlightsweekQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getSearchHighlightsweekQueryKey(params);
  return queryOptions<
    GetSearchHighlightsweekQueryResponse,
    ResponseErrorConfig<
      GetSearchHighlightsweek400 | GetSearchHighlightsweek500
    >,
    GetSearchHighlightsweekQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getSearchHighlightsweek(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna uma lista paginada de até 10 profissionais que são destaques da semana. A paginação é controlada pelo query param `page`.
 * @summary Pesquisa os profissionais destaques da semana
 * {@link /search/highlightsWeek}
 */
export function useGetSearchHighlightsweek<
  TData = GetSearchHighlightsweekQueryResponse,
  TQueryData = GetSearchHighlightsweekQueryResponse,
  TQueryKey extends QueryKey = GetSearchHighlightsweekQueryKey,
>(
  params?: GetSearchHighlightsweekQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetSearchHighlightsweekQueryResponse,
        ResponseErrorConfig<
          GetSearchHighlightsweek400 | GetSearchHighlightsweek500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getSearchHighlightsweekQueryKey(params);

  const query = useQuery(
    {
      ...getSearchHighlightsweekQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetSearchHighlightsweek400 | GetSearchHighlightsweek500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
