/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { GetTesteQueryResponse } from "../types/GetTeste.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getTesteQueryKey = () => [{ url: "/teste" }] as const;

export type GetTesteQueryKey = ReturnType<typeof getTesteQueryKey>;

/**
 * @summary Teste para verificar se API está funcionando
 * {@link /teste}
 */
export async function getTeste(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTesteQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/teste`, ...requestConfig });
  return res.data;
}

export function getTesteQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getTesteQueryKey();
  return queryOptions<
    GetTesteQueryResponse,
    ResponseErrorConfig<Error>,
    GetTesteQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getTeste({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary Teste para verificar se API está funcionando
 * {@link /teste}
 */
export function useGetTeste<
  TData = GetTesteQueryResponse,
  TQueryData = GetTesteQueryResponse,
  TQueryKey extends QueryKey = GetTesteQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetTesteQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getTesteQueryKey();

  const query = useQuery(
    {
      ...getTesteQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
