/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetSearchProfessionalsQueryResponse,
  GetSearchProfessionalsQueryParams,
  GetSearchProfessionals500,
} from "../types/GetSearchProfessionals.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getSearchProfessionalsSuspenseQueryKey = (
  params?: GetSearchProfessionalsQueryParams,
) => [{ url: "/search/professionals" }, ...(params ? [params] : [])] as const;

export type GetSearchProfessionalsSuspenseQueryKey = ReturnType<
  typeof getSearchProfessionalsSuspenseQueryKey
>;

/**
 * @description Retorna profissionais com filtros opcionais de especialidade, acessibilidade e tipo de serviço. Os filtros podem ser combinados (AND).
 * @summary Lista profissionais com filtros combinados
 * {@link /search/professionals}
 */
export async function getSearchProfessionalsSuspense(
  params?: GetSearchProfessionalsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetSearchProfessionalsQueryResponse,
    ResponseErrorConfig<GetSearchProfessionals500>,
    unknown
  >({ method: "GET", url: `/search/professionals`, params, ...requestConfig });
  return res.data;
}

export function getSearchProfessionalsSuspenseQueryOptions(
  params?: GetSearchProfessionalsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getSearchProfessionalsSuspenseQueryKey(params);
  return queryOptions<
    GetSearchProfessionalsQueryResponse,
    ResponseErrorConfig<GetSearchProfessionals500>,
    GetSearchProfessionalsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getSearchProfessionalsSuspense(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna profissionais com filtros opcionais de especialidade, acessibilidade e tipo de serviço. Os filtros podem ser combinados (AND).
 * @summary Lista profissionais com filtros combinados
 * {@link /search/professionals}
 */
export function useGetSearchProfessionalsSuspense<
  TData = GetSearchProfessionalsQueryResponse,
  TQueryKey extends QueryKey = GetSearchProfessionalsSuspenseQueryKey,
>(
  params?: GetSearchProfessionalsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetSearchProfessionalsQueryResponse,
        ResponseErrorConfig<GetSearchProfessionals500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getSearchProfessionalsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getSearchProfessionalsSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetSearchProfessionals500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
