/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetMessagesUnreadQueryResponse,
  GetMessagesUnreadHeaderParams,
  GetMessagesUnread401,
  GetMessagesUnread403,
  GetMessagesUnread500,
} from "../types/GetMessagesUnread.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMessagesUnreadQueryKey = () =>
  [{ url: "/messages/unread" }] as const;

export type GetMessagesUnreadQueryKey = ReturnType<
  typeof getMessagesUnreadQueryKey
>;

/**
 * @description Retorna apenas as conversas onde o usuário logado possui mensagens não lidas (unreadCount > 0).
 * @summary Listar conversas com mensagens não lidas
 * {@link /messages/unread}
 */
export async function getMessagesUnread(
  headers: GetMessagesUnreadHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetMessagesUnreadQueryResponse,
    ResponseErrorConfig<
      GetMessagesUnread401 | GetMessagesUnread403 | GetMessagesUnread500
    >,
    unknown
  >({
    method: "GET",
    url: `/messages/unread`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function getMessagesUnreadQueryOptions(
  headers: GetMessagesUnreadHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getMessagesUnreadQueryKey();
  return queryOptions<
    GetMessagesUnreadQueryResponse,
    ResponseErrorConfig<
      GetMessagesUnread401 | GetMessagesUnread403 | GetMessagesUnread500
    >,
    GetMessagesUnreadQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getMessagesUnread(headers, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna apenas as conversas onde o usuário logado possui mensagens não lidas (unreadCount > 0).
 * @summary Listar conversas com mensagens não lidas
 * {@link /messages/unread}
 */
export function useGetMessagesUnread<
  TData = GetMessagesUnreadQueryResponse,
  TQueryData = GetMessagesUnreadQueryResponse,
  TQueryKey extends QueryKey = GetMessagesUnreadQueryKey,
>(
  headers: GetMessagesUnreadHeaderParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetMessagesUnreadQueryResponse,
        ResponseErrorConfig<
          GetMessagesUnread401 | GetMessagesUnread403 | GetMessagesUnread500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getMessagesUnreadQueryKey();

  const query = useQuery(
    {
      ...getMessagesUnreadQueryOptions(headers, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      GetMessagesUnread401 | GetMessagesUnread403 | GetMessagesUnread500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
