/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetSearchSearchbarTermsQueryResponse,
  GetSearchSearchbarTermsPathParams,
  GetSearchSearchbarTerms400,
  GetSearchSearchbarTerms500,
} from "../types/GetSearchSearchbarTerms.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getSearchSearchbarTermsQueryKey = (
  terms: GetSearchSearchbarTermsPathParams["terms"],
  page: GetSearchSearchbarTermsPathParams["page"],
) => [{ url: "/search/searchBar/:terms", params: { terms: terms } }] as const;

export type GetSearchSearchbarTermsQueryKey = ReturnType<
  typeof getSearchSearchbarTermsQueryKey
>;

/**
 * @description Retorna até 10 profissionais por página, pesquisando pelo nome ou pela especialidade. A busca é case-insensitive e suporta paginação.
 * @summary Busca de profissionais pela barra de pesquisa
 * {@link /search/searchBar/:terms}
 */
export async function getSearchSearchbarTerms(
  terms: GetSearchSearchbarTermsPathParams["terms"],
  page: GetSearchSearchbarTermsPathParams["page"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetSearchSearchbarTermsQueryResponse,
    ResponseErrorConfig<
      GetSearchSearchbarTerms400 | GetSearchSearchbarTerms500
    >,
    unknown
  >({ method: "GET", url: `/search/searchBar/${terms}`, ...requestConfig });
  return res.data;
}

export function getSearchSearchbarTermsQueryOptions(
  terms: GetSearchSearchbarTermsPathParams["terms"],
  page: GetSearchSearchbarTermsPathParams["page"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getSearchSearchbarTermsQueryKey(terms, page);
  return queryOptions<
    GetSearchSearchbarTermsQueryResponse,
    ResponseErrorConfig<
      GetSearchSearchbarTerms400 | GetSearchSearchbarTerms500
    >,
    GetSearchSearchbarTermsQueryResponse,
    typeof queryKey
  >({
    enabled: !!(terms && page),
    queryKey,
    queryFn: async ({ signal }) => {
      return getSearchSearchbarTerms(terms, page, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna até 10 profissionais por página, pesquisando pelo nome ou pela especialidade. A busca é case-insensitive e suporta paginação.
 * @summary Busca de profissionais pela barra de pesquisa
 * {@link /search/searchBar/:terms}
 */
export function useGetSearchSearchbarTerms<
  TData = GetSearchSearchbarTermsQueryResponse,
  TQueryData = GetSearchSearchbarTermsQueryResponse,
  TQueryKey extends QueryKey = GetSearchSearchbarTermsQueryKey,
>(
  terms: GetSearchSearchbarTermsPathParams["terms"],
  page: GetSearchSearchbarTermsPathParams["page"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetSearchSearchbarTermsQueryResponse,
        ResponseErrorConfig<
          GetSearchSearchbarTerms400 | GetSearchSearchbarTerms500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getSearchSearchbarTermsQueryKey(terms, page);

  const query = useQuery(
    {
      ...getSearchSearchbarTermsQueryOptions(terms, page, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetSearchSearchbarTerms400 | GetSearchSearchbarTerms500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
