/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostAppointmentsMutationRequest,
  PostAppointmentsMutationResponse,
  PostAppointmentsHeaderParams,
  PostAppointments400,
  PostAppointments401,
  PostAppointments403,
  PostAppointments409,
  PostAppointments422,
  PostAppointments500,
} from "../types/PostAppointments.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postAppointmentsMutationKey = () =>
  [{ url: "/appointments" }] as const;

export type PostAppointmentsMutationKey = ReturnType<
  typeof postAppointmentsMutationKey
>;

/**
 * @description Paciente cria uma solicitação para um profissional em data/hora escolhidas.
 * @summary Criar solicitação de agendamento (paciente)
 * {@link /appointments}
 */
export async function postAppointments(
  data: PostAppointmentsMutationRequest,
  headers: PostAppointmentsHeaderParams,
  config: Partial<RequestConfig<PostAppointmentsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostAppointmentsMutationResponse,
    ResponseErrorConfig<
      | PostAppointments400
      | PostAppointments401
      | PostAppointments403
      | PostAppointments409
      | PostAppointments422
      | PostAppointments500
    >,
    PostAppointmentsMutationRequest
  >({
    method: "POST",
    url: `/appointments`,
    data: requestData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function postAppointmentsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostAppointmentsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postAppointmentsMutationKey();
  return mutationOptions<
    PostAppointmentsMutationResponse,
    ResponseErrorConfig<
      | PostAppointments400
      | PostAppointments401
      | PostAppointments403
      | PostAppointments409
      | PostAppointments422
      | PostAppointments500
    >,
    {
      data: PostAppointmentsMutationRequest;
      headers: PostAppointmentsHeaderParams;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data, headers }) => {
      return postAppointments(data, headers, config);
    },
  });
}

/**
 * @description Paciente cria uma solicitação para um profissional em data/hora escolhidas.
 * @summary Criar solicitação de agendamento (paciente)
 * {@link /appointments}
 */
export function usePostAppointments<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAppointmentsMutationResponse,
      ResponseErrorConfig<
        | PostAppointments400
        | PostAppointments401
        | PostAppointments403
        | PostAppointments409
        | PostAppointments422
        | PostAppointments500
      >,
      {
        data: PostAppointmentsMutationRequest;
        headers: PostAppointmentsHeaderParams;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostAppointmentsMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postAppointmentsMutationKey();

  const baseOptions = postAppointmentsMutationOptions(
    config,
  ) as UseMutationOptions<
    PostAppointmentsMutationResponse,
    ResponseErrorConfig<
      | PostAppointments400
      | PostAppointments401
      | PostAppointments403
      | PostAppointments409
      | PostAppointments422
      | PostAppointments500
    >,
    {
      data: PostAppointmentsMutationRequest;
      headers: PostAppointmentsHeaderParams;
    },
    TContext
  >;

  return useMutation<
    PostAppointmentsMutationResponse,
    ResponseErrorConfig<
      | PostAppointments400
      | PostAppointments401
      | PostAppointments403
      | PostAppointments409
      | PostAppointments422
      | PostAppointments500
    >,
    {
      data: PostAppointmentsMutationRequest;
      headers: PostAppointmentsHeaderParams;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostAppointmentsMutationResponse,
    ResponseErrorConfig<
      | PostAppointments400
      | PostAppointments401
      | PostAppointments403
      | PostAppointments409
      | PostAppointments422
      | PostAppointments500
    >,
    {
      data: PostAppointmentsMutationRequest;
      headers: PostAppointmentsHeaderParams;
    },
    TContext
  >;
}
