/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PatchConversationsConversationidReadMutationResponse,
  PatchConversationsConversationidReadPathParams,
  PatchConversationsConversationidReadHeaderParams,
  PatchConversationsConversationidRead401,
  PatchConversationsConversationidRead403,
  PatchConversationsConversationidRead404,
  PatchConversationsConversationidRead500,
} from "../types/PatchConversationsConversationidRead.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchConversationsConversationidReadMutationKey = () =>
  [{ url: "/conversations/:conversationId/read" }] as const;

export type PatchConversationsConversationidReadMutationKey = ReturnType<
  typeof patchConversationsConversationidReadMutationKey
>;

/**
 * @description Zera o campo unreadCount do usuário autenticado nessa conversa.
 * @summary Marcar conversa como lida
 * {@link /conversations/:conversationId/read}
 */
export async function patchConversationsConversationidRead(
  conversationId: PatchConversationsConversationidReadPathParams["conversationId"],
  headers: PatchConversationsConversationidReadHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PatchConversationsConversationidReadMutationResponse,
    ResponseErrorConfig<
      | PatchConversationsConversationidRead401
      | PatchConversationsConversationidRead403
      | PatchConversationsConversationidRead404
      | PatchConversationsConversationidRead500
    >,
    unknown
  >({
    method: "PATCH",
    url: `/conversations/${conversationId}/read`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function patchConversationsConversationidReadMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = patchConversationsConversationidReadMutationKey();
  return mutationOptions<
    PatchConversationsConversationidReadMutationResponse,
    ResponseErrorConfig<
      | PatchConversationsConversationidRead401
      | PatchConversationsConversationidRead403
      | PatchConversationsConversationidRead404
      | PatchConversationsConversationidRead500
    >,
    {
      conversationId: PatchConversationsConversationidReadPathParams["conversationId"];
      headers: PatchConversationsConversationidReadHeaderParams;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ conversationId, headers }) => {
      return patchConversationsConversationidRead(
        conversationId,
        headers,
        config,
      );
    },
  });
}

/**
 * @description Zera o campo unreadCount do usuário autenticado nessa conversa.
 * @summary Marcar conversa como lida
 * {@link /conversations/:conversationId/read}
 */
export function usePatchConversationsConversationidRead<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchConversationsConversationidReadMutationResponse,
      ResponseErrorConfig<
        | PatchConversationsConversationidRead401
        | PatchConversationsConversationidRead403
        | PatchConversationsConversationidRead404
        | PatchConversationsConversationidRead500
      >,
      {
        conversationId: PatchConversationsConversationidReadPathParams["conversationId"];
        headers: PatchConversationsConversationidReadHeaderParams;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    patchConversationsConversationidReadMutationKey();

  const baseOptions = patchConversationsConversationidReadMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchConversationsConversationidReadMutationResponse,
    ResponseErrorConfig<
      | PatchConversationsConversationidRead401
      | PatchConversationsConversationidRead403
      | PatchConversationsConversationidRead404
      | PatchConversationsConversationidRead500
    >,
    {
      conversationId: PatchConversationsConversationidReadPathParams["conversationId"];
      headers: PatchConversationsConversationidReadHeaderParams;
    },
    TContext
  >;

  return useMutation<
    PatchConversationsConversationidReadMutationResponse,
    ResponseErrorConfig<
      | PatchConversationsConversationidRead401
      | PatchConversationsConversationidRead403
      | PatchConversationsConversationidRead404
      | PatchConversationsConversationidRead500
    >,
    {
      conversationId: PatchConversationsConversationidReadPathParams["conversationId"];
      headers: PatchConversationsConversationidReadHeaderParams;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchConversationsConversationidReadMutationResponse,
    ResponseErrorConfig<
      | PatchConversationsConversationidRead401
      | PatchConversationsConversationidRead403
      | PatchConversationsConversationidRead404
      | PatchConversationsConversationidRead500
    >,
    {
      conversationId: PatchConversationsConversationidReadPathParams["conversationId"];
      headers: PatchConversationsConversationidReadHeaderParams;
    },
    TContext
  >;
}
