/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostAuthCheckotpMutationRequest,
  PostAuthCheckotpMutationResponse,
  PostAuthCheckotp401,
  PostAuthCheckotp422,
  PostAuthCheckotp429,
  PostAuthCheckotp500,
} from "../types/PostAuthCheckotp.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postAuthCheckotpMutationKey = () =>
  [{ url: "/auth/checkOTP" }] as const;

export type PostAuthCheckotpMutationKey = ReturnType<
  typeof postAuthCheckotpMutationKey
>;

/**
 * @description Verifica se o OTP enviado no body corresponde ao OTP encriptado no backend. Se coincidir: se o usuário já existir, é logado; caso contrário, fica liberado para registro.
 * @summary Checa se OTP coincide e realiza login/registro
 * {@link /auth/checkOTP}
 */
export async function postAuthCheckotp(
  data: PostAuthCheckotpMutationRequest,
  config: Partial<RequestConfig<PostAuthCheckotpMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostAuthCheckotpMutationResponse,
    ResponseErrorConfig<
      | PostAuthCheckotp401
      | PostAuthCheckotp422
      | PostAuthCheckotp429
      | PostAuthCheckotp500
    >,
    PostAuthCheckotpMutationRequest
  >({
    method: "POST",
    url: `/auth/checkOTP`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function postAuthCheckotpMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostAuthCheckotpMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postAuthCheckotpMutationKey();
  return mutationOptions<
    PostAuthCheckotpMutationResponse,
    ResponseErrorConfig<
      | PostAuthCheckotp401
      | PostAuthCheckotp422
      | PostAuthCheckotp429
      | PostAuthCheckotp500
    >,
    { data: PostAuthCheckotpMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postAuthCheckotp(data, config);
    },
  });
}

/**
 * @description Verifica se o OTP enviado no body corresponde ao OTP encriptado no backend. Se coincidir: se o usuário já existir, é logado; caso contrário, fica liberado para registro.
 * @summary Checa se OTP coincide e realiza login/registro
 * {@link /auth/checkOTP}
 */
export function usePostAuthCheckotp<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAuthCheckotpMutationResponse,
      ResponseErrorConfig<
        | PostAuthCheckotp401
        | PostAuthCheckotp422
        | PostAuthCheckotp429
        | PostAuthCheckotp500
      >,
      { data: PostAuthCheckotpMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostAuthCheckotpMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postAuthCheckotpMutationKey();

  const baseOptions = postAuthCheckotpMutationOptions(
    config,
  ) as UseMutationOptions<
    PostAuthCheckotpMutationResponse,
    ResponseErrorConfig<
      | PostAuthCheckotp401
      | PostAuthCheckotp422
      | PostAuthCheckotp429
      | PostAuthCheckotp500
    >,
    { data: PostAuthCheckotpMutationRequest },
    TContext
  >;

  return useMutation<
    PostAuthCheckotpMutationResponse,
    ResponseErrorConfig<
      | PostAuthCheckotp401
      | PostAuthCheckotp422
      | PostAuthCheckotp429
      | PostAuthCheckotp500
    >,
    { data: PostAuthCheckotpMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostAuthCheckotpMutationResponse,
    ResponseErrorConfig<
      | PostAuthCheckotp401
      | PostAuthCheckotp422
      | PostAuthCheckotp429
      | PostAuthCheckotp500
    >,
    { data: PostAuthCheckotpMutationRequest },
    TContext
  >;
}
