/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PutAddressMutationRequest,
  PutAddressMutationResponse,
  PutAddressHeaderParams,
  PutAddress401,
  PutAddress403,
  PutAddress422,
  PutAddress500,
} from "../types/PutAddress.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putAddressMutationKey = () => [{ url: "/address" }] as const;

export type PutAddressMutationKey = ReturnType<typeof putAddressMutationKey>;

/**
 * @description Endpoint protegido que atualiza um endereço existente de um usuário logado. É necessário fornecer o ID do endereço e os novos dados no corpo da requisição.
 * @summary Atualiza um endereço do usuário
 * {@link /address}
 */
export async function putAddress(
  data: PutAddressMutationRequest,
  headers?: PutAddressHeaderParams,
  config: Partial<RequestConfig<PutAddressMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PutAddressMutationResponse,
    ResponseErrorConfig<
      PutAddress401 | PutAddress403 | PutAddress422 | PutAddress500
    >,
    PutAddressMutationRequest
  >({
    method: "PUT",
    url: `/address`,
    data: requestData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function putAddressMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PutAddressMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = putAddressMutationKey();
  return mutationOptions<
    PutAddressMutationResponse,
    ResponseErrorConfig<
      PutAddress401 | PutAddress403 | PutAddress422 | PutAddress500
    >,
    { data: PutAddressMutationRequest; headers?: PutAddressHeaderParams },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data, headers }) => {
      return putAddress(data, headers, config);
    },
  });
}

/**
 * @description Endpoint protegido que atualiza um endereço existente de um usuário logado. É necessário fornecer o ID do endereço e os novos dados no corpo da requisição.
 * @summary Atualiza um endereço do usuário
 * {@link /address}
 */
export function usePutAddress<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PutAddressMutationResponse,
      ResponseErrorConfig<
        PutAddress401 | PutAddress403 | PutAddress422 | PutAddress500
      >,
      { data: PutAddressMutationRequest; headers?: PutAddressHeaderParams },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PutAddressMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putAddressMutationKey();

  const baseOptions = putAddressMutationOptions(config) as UseMutationOptions<
    PutAddressMutationResponse,
    ResponseErrorConfig<
      PutAddress401 | PutAddress403 | PutAddress422 | PutAddress500
    >,
    { data: PutAddressMutationRequest; headers?: PutAddressHeaderParams },
    TContext
  >;

  return useMutation<
    PutAddressMutationResponse,
    ResponseErrorConfig<
      PutAddress401 | PutAddress403 | PutAddress422 | PutAddress500
    >,
    { data: PutAddressMutationRequest; headers?: PutAddressHeaderParams },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PutAddressMutationResponse,
    ResponseErrorConfig<
      PutAddress401 | PutAddress403 | PutAddress422 | PutAddress500
    >,
    { data: PutAddressMutationRequest; headers?: PutAddressHeaderParams },
    TContext
  >;
}
