/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostWebhooksMessageCreatedMutationRequest,
  PostWebhooksMessageCreatedMutationResponse,
  PostWebhooksMessageCreatedHeaderParams,
  PostWebhooksMessageCreated401,
} from "../types/PostWebhooksMessageCreated.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postWebhooksMessageCreatedMutationKey = () =>
  [{ url: "/webhooks/message-created" }] as const;

export type PostWebhooksMessageCreatedMutationKey = ReturnType<
  typeof postWebhooksMessageCreatedMutationKey
>;

/**
 * @summary Evento enviado quando uma nova mensagem é criada
 * {@link /webhooks/message-created}
 */
export async function postWebhooksMessageCreated(
  data: PostWebhooksMessageCreatedMutationRequest,
  headers: PostWebhooksMessageCreatedHeaderParams,
  config: Partial<RequestConfig<PostWebhooksMessageCreatedMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostWebhooksMessageCreatedMutationResponse,
    ResponseErrorConfig<PostWebhooksMessageCreated401>,
    PostWebhooksMessageCreatedMutationRequest
  >({
    method: "POST",
    url: `/webhooks/message-created`,
    data: requestData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function postWebhooksMessageCreatedMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostWebhooksMessageCreatedMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postWebhooksMessageCreatedMutationKey();
  return mutationOptions<
    PostWebhooksMessageCreatedMutationResponse,
    ResponseErrorConfig<PostWebhooksMessageCreated401>,
    {
      data: PostWebhooksMessageCreatedMutationRequest;
      headers: PostWebhooksMessageCreatedHeaderParams;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data, headers }) => {
      return postWebhooksMessageCreated(data, headers, config);
    },
  });
}

/**
 * @summary Evento enviado quando uma nova mensagem é criada
 * {@link /webhooks/message-created}
 */
export function usePostWebhooksMessageCreated<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostWebhooksMessageCreatedMutationResponse,
      ResponseErrorConfig<PostWebhooksMessageCreated401>,
      {
        data: PostWebhooksMessageCreatedMutationRequest;
        headers: PostWebhooksMessageCreatedHeaderParams;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostWebhooksMessageCreatedMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postWebhooksMessageCreatedMutationKey();

  const baseOptions = postWebhooksMessageCreatedMutationOptions(
    config,
  ) as UseMutationOptions<
    PostWebhooksMessageCreatedMutationResponse,
    ResponseErrorConfig<PostWebhooksMessageCreated401>,
    {
      data: PostWebhooksMessageCreatedMutationRequest;
      headers: PostWebhooksMessageCreatedHeaderParams;
    },
    TContext
  >;

  return useMutation<
    PostWebhooksMessageCreatedMutationResponse,
    ResponseErrorConfig<PostWebhooksMessageCreated401>,
    {
      data: PostWebhooksMessageCreatedMutationRequest;
      headers: PostWebhooksMessageCreatedHeaderParams;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostWebhooksMessageCreatedMutationResponse,
    ResponseErrorConfig<PostWebhooksMessageCreated401>,
    {
      data: PostWebhooksMessageCreatedMutationRequest;
      headers: PostWebhooksMessageCreatedHeaderParams;
    },
    TContext
  >;
}
