/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostAuthCreateprofessionalMutationRequest,
  PostAuthCreateprofessionalMutationResponse,
  PostAuthCreateprofessionalHeaderParams,
  PostAuthCreateprofessional401,
  PostAuthCreateprofessional403,
  PostAuthCreateprofessional404,
  PostAuthCreateprofessional422,
  PostAuthCreateprofessional500,
} from "../types/PostAuthCreateprofessional.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postAuthCreateprofessionalMutationKey = () =>
  [{ url: "/auth/createProfessional" }] as const;

export type PostAuthCreateprofessionalMutationKey = ReturnType<
  typeof postAuthCreateprofessionalMutationKey
>;

/**
 * @description Finaliza o cadastro do profissional após os passos de sendOTP e checkOTP. É necessário que o usuário já exista como pendente antes de chamar este endpoint.
 * @summary Completa o cadastro do usuário profissional
 * {@link /auth/createProfessional}
 */
export async function postAuthCreateprofessional(
  data: PostAuthCreateprofessionalMutationRequest,
  headers?: PostAuthCreateprofessionalHeaderParams,
  config: Partial<RequestConfig<PostAuthCreateprofessionalMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostAuthCreateprofessionalMutationResponse,
    ResponseErrorConfig<
      | PostAuthCreateprofessional401
      | PostAuthCreateprofessional403
      | PostAuthCreateprofessional404
      | PostAuthCreateprofessional422
      | PostAuthCreateprofessional500
    >,
    PostAuthCreateprofessionalMutationRequest
  >({
    method: "POST",
    url: `/auth/createProfessional`,
    data: requestData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function postAuthCreateprofessionalMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostAuthCreateprofessionalMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postAuthCreateprofessionalMutationKey();
  return mutationOptions<
    PostAuthCreateprofessionalMutationResponse,
    ResponseErrorConfig<
      | PostAuthCreateprofessional401
      | PostAuthCreateprofessional403
      | PostAuthCreateprofessional404
      | PostAuthCreateprofessional422
      | PostAuthCreateprofessional500
    >,
    {
      data: PostAuthCreateprofessionalMutationRequest;
      headers?: PostAuthCreateprofessionalHeaderParams;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data, headers }) => {
      return postAuthCreateprofessional(data, headers, config);
    },
  });
}

/**
 * @description Finaliza o cadastro do profissional após os passos de sendOTP e checkOTP. É necessário que o usuário já exista como pendente antes de chamar este endpoint.
 * @summary Completa o cadastro do usuário profissional
 * {@link /auth/createProfessional}
 */
export function usePostAuthCreateprofessional<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAuthCreateprofessionalMutationResponse,
      ResponseErrorConfig<
        | PostAuthCreateprofessional401
        | PostAuthCreateprofessional403
        | PostAuthCreateprofessional404
        | PostAuthCreateprofessional422
        | PostAuthCreateprofessional500
      >,
      {
        data: PostAuthCreateprofessionalMutationRequest;
        headers?: PostAuthCreateprofessionalHeaderParams;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostAuthCreateprofessionalMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postAuthCreateprofessionalMutationKey();

  const baseOptions = postAuthCreateprofessionalMutationOptions(
    config,
  ) as UseMutationOptions<
    PostAuthCreateprofessionalMutationResponse,
    ResponseErrorConfig<
      | PostAuthCreateprofessional401
      | PostAuthCreateprofessional403
      | PostAuthCreateprofessional404
      | PostAuthCreateprofessional422
      | PostAuthCreateprofessional500
    >,
    {
      data: PostAuthCreateprofessionalMutationRequest;
      headers?: PostAuthCreateprofessionalHeaderParams;
    },
    TContext
  >;

  return useMutation<
    PostAuthCreateprofessionalMutationResponse,
    ResponseErrorConfig<
      | PostAuthCreateprofessional401
      | PostAuthCreateprofessional403
      | PostAuthCreateprofessional404
      | PostAuthCreateprofessional422
      | PostAuthCreateprofessional500
    >,
    {
      data: PostAuthCreateprofessionalMutationRequest;
      headers?: PostAuthCreateprofessionalHeaderParams;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostAuthCreateprofessionalMutationResponse,
    ResponseErrorConfig<
      | PostAuthCreateprofessional401
      | PostAuthCreateprofessional403
      | PostAuthCreateprofessional404
      | PostAuthCreateprofessional422
      | PostAuthCreateprofessional500
    >,
    {
      data: PostAuthCreateprofessionalMutationRequest;
      headers?: PostAuthCreateprofessionalHeaderParams;
    },
    TContext
  >;
}
