/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostMessagesMutationRequest,
  PostMessagesMutationResponse,
  PostMessagesHeaderParams,
  PostMessages400,
  PostMessages401,
  PostMessages403,
  PostMessages500,
} from "../types/PostMessages.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postMessagesMutationKey = () => [{ url: "/messages" }] as const;

export type PostMessagesMutationKey = ReturnType<
  typeof postMessagesMutationKey
>;

/**
 * @description Cria uma nova mensagem em uma conversa existente ou inicia uma nova conversa caso não seja informado um ID. Atualiza o lastMessage e incrementa o unreadCount dos participantes.
 * @summary Enviar mensagem em uma conversa
 * {@link /messages}
 */
export async function postMessages(
  data: PostMessagesMutationRequest,
  headers: PostMessagesHeaderParams,
  config: Partial<RequestConfig<PostMessagesMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostMessagesMutationResponse,
    ResponseErrorConfig<
      PostMessages400 | PostMessages401 | PostMessages403 | PostMessages500
    >,
    PostMessagesMutationRequest
  >({
    method: "POST",
    url: `/messages`,
    data: requestData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function postMessagesMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostMessagesMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postMessagesMutationKey();
  return mutationOptions<
    PostMessagesMutationResponse,
    ResponseErrorConfig<
      PostMessages400 | PostMessages401 | PostMessages403 | PostMessages500
    >,
    { data: PostMessagesMutationRequest; headers: PostMessagesHeaderParams },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data, headers }) => {
      return postMessages(data, headers, config);
    },
  });
}

/**
 * @description Cria uma nova mensagem em uma conversa existente ou inicia uma nova conversa caso não seja informado um ID. Atualiza o lastMessage e incrementa o unreadCount dos participantes.
 * @summary Enviar mensagem em uma conversa
 * {@link /messages}
 */
export function usePostMessages<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostMessagesMutationResponse,
      ResponseErrorConfig<
        PostMessages400 | PostMessages401 | PostMessages403 | PostMessages500
      >,
      { data: PostMessagesMutationRequest; headers: PostMessagesHeaderParams },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostMessagesMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postMessagesMutationKey();

  const baseOptions = postMessagesMutationOptions(config) as UseMutationOptions<
    PostMessagesMutationResponse,
    ResponseErrorConfig<
      PostMessages400 | PostMessages401 | PostMessages403 | PostMessages500
    >,
    { data: PostMessagesMutationRequest; headers: PostMessagesHeaderParams },
    TContext
  >;

  return useMutation<
    PostMessagesMutationResponse,
    ResponseErrorConfig<
      PostMessages400 | PostMessages401 | PostMessages403 | PostMessages500
    >,
    { data: PostMessagesMutationRequest; headers: PostMessagesHeaderParams },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostMessagesMutationResponse,
    ResponseErrorConfig<
      PostMessages400 | PostMessages401 | PostMessages403 | PostMessages500
    >,
    { data: PostMessagesMutationRequest; headers: PostMessagesHeaderParams },
    TContext
  >;
}
