/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PutActiveAddressMutationRequest,
  PutActiveAddressMutationResponse,
  PutActiveAddressHeaderParams,
  PutActiveAddress401,
  PutActiveAddress403,
  PutActiveAddress404,
  PutActiveAddress422,
  PutActiveAddress500,
} from "../types/PutActiveAddress.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putActiveAddressMutationKey = () =>
  [{ url: "/active-address" }] as const;

export type PutActiveAddressMutationKey = ReturnType<
  typeof putActiveAddressMutationKey
>;

/**
 * @description Endpoint protegido que define um endereço como principal (ativo) para o usuário logado. O campo `addressId` é obrigatório.
 * @summary Alterar endereço principal do usuário
 * {@link /active-address}
 */
export async function putActiveAddress(
  data: PutActiveAddressMutationRequest,
  headers?: PutActiveAddressHeaderParams,
  config: Partial<RequestConfig<PutActiveAddressMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PutActiveAddressMutationResponse,
    ResponseErrorConfig<
      | PutActiveAddress401
      | PutActiveAddress403
      | PutActiveAddress404
      | PutActiveAddress422
      | PutActiveAddress500
    >,
    PutActiveAddressMutationRequest
  >({
    method: "PUT",
    url: `/active-address`,
    data: requestData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function putActiveAddressMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PutActiveAddressMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = putActiveAddressMutationKey();
  return mutationOptions<
    PutActiveAddressMutationResponse,
    ResponseErrorConfig<
      | PutActiveAddress401
      | PutActiveAddress403
      | PutActiveAddress404
      | PutActiveAddress422
      | PutActiveAddress500
    >,
    {
      data: PutActiveAddressMutationRequest;
      headers?: PutActiveAddressHeaderParams;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data, headers }) => {
      return putActiveAddress(data, headers, config);
    },
  });
}

/**
 * @description Endpoint protegido que define um endereço como principal (ativo) para o usuário logado. O campo `addressId` é obrigatório.
 * @summary Alterar endereço principal do usuário
 * {@link /active-address}
 */
export function usePutActiveAddress<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PutActiveAddressMutationResponse,
      ResponseErrorConfig<
        | PutActiveAddress401
        | PutActiveAddress403
        | PutActiveAddress404
        | PutActiveAddress422
        | PutActiveAddress500
      >,
      {
        data: PutActiveAddressMutationRequest;
        headers?: PutActiveAddressHeaderParams;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PutActiveAddressMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? putActiveAddressMutationKey();

  const baseOptions = putActiveAddressMutationOptions(
    config,
  ) as UseMutationOptions<
    PutActiveAddressMutationResponse,
    ResponseErrorConfig<
      | PutActiveAddress401
      | PutActiveAddress403
      | PutActiveAddress404
      | PutActiveAddress422
      | PutActiveAddress500
    >,
    {
      data: PutActiveAddressMutationRequest;
      headers?: PutActiveAddressHeaderParams;
    },
    TContext
  >;

  return useMutation<
    PutActiveAddressMutationResponse,
    ResponseErrorConfig<
      | PutActiveAddress401
      | PutActiveAddress403
      | PutActiveAddress404
      | PutActiveAddress422
      | PutActiveAddress500
    >,
    {
      data: PutActiveAddressMutationRequest;
      headers?: PutActiveAddressHeaderParams;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PutActiveAddressMutationResponse,
    ResponseErrorConfig<
      | PutActiveAddress401
      | PutActiveAddress403
      | PutActiveAddress404
      | PutActiveAddress422
      | PutActiveAddress500
    >,
    {
      data: PutActiveAddressMutationRequest;
      headers?: PutActiveAddressHeaderParams;
    },
    TContext
  >;
}
