/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostAuthCreatepatientMutationRequest,
  PostAuthCreatepatientMutationResponse,
  PostAuthCreatepatientHeaderParams,
  PostAuthCreatepatient401,
  PostAuthCreatepatient403,
  PostAuthCreatepatient404,
  PostAuthCreatepatient422,
  PostAuthCreatepatient500,
} from "../types/PostAuthCreatepatient.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postAuthCreatepatientMutationKey = () =>
  [{ url: "/auth/createPatient" }] as const;

export type PostAuthCreatepatientMutationKey = ReturnType<
  typeof postAuthCreatepatientMutationKey
>;

/**
 * @description Este endpoint finaliza o cadastro do paciente após o fluxo de sendOTP e checkOTP. É necessário já existir um usuário pendente antes da chamada.
 * @summary Completa o cadastro do usuário paciente
 * {@link /auth/createPatient}
 */
export async function postAuthCreatepatient(
  data: PostAuthCreatepatientMutationRequest,
  headers?: PostAuthCreatepatientHeaderParams,
  config: Partial<RequestConfig<PostAuthCreatepatientMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostAuthCreatepatientMutationResponse,
    ResponseErrorConfig<
      | PostAuthCreatepatient401
      | PostAuthCreatepatient403
      | PostAuthCreatepatient404
      | PostAuthCreatepatient422
      | PostAuthCreatepatient500
    >,
    PostAuthCreatepatientMutationRequest
  >({
    method: "POST",
    url: `/auth/createPatient`,
    data: requestData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function postAuthCreatepatientMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostAuthCreatepatientMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postAuthCreatepatientMutationKey();
  return mutationOptions<
    PostAuthCreatepatientMutationResponse,
    ResponseErrorConfig<
      | PostAuthCreatepatient401
      | PostAuthCreatepatient403
      | PostAuthCreatepatient404
      | PostAuthCreatepatient422
      | PostAuthCreatepatient500
    >,
    {
      data: PostAuthCreatepatientMutationRequest;
      headers?: PostAuthCreatepatientHeaderParams;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data, headers }) => {
      return postAuthCreatepatient(data, headers, config);
    },
  });
}

/**
 * @description Este endpoint finaliza o cadastro do paciente após o fluxo de sendOTP e checkOTP. É necessário já existir um usuário pendente antes da chamada.
 * @summary Completa o cadastro do usuário paciente
 * {@link /auth/createPatient}
 */
export function usePostAuthCreatepatient<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAuthCreatepatientMutationResponse,
      ResponseErrorConfig<
        | PostAuthCreatepatient401
        | PostAuthCreatepatient403
        | PostAuthCreatepatient404
        | PostAuthCreatepatient422
        | PostAuthCreatepatient500
      >,
      {
        data: PostAuthCreatepatientMutationRequest;
        headers?: PostAuthCreatepatientHeaderParams;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostAuthCreatepatientMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postAuthCreatepatientMutationKey();

  const baseOptions = postAuthCreatepatientMutationOptions(
    config,
  ) as UseMutationOptions<
    PostAuthCreatepatientMutationResponse,
    ResponseErrorConfig<
      | PostAuthCreatepatient401
      | PostAuthCreatepatient403
      | PostAuthCreatepatient404
      | PostAuthCreatepatient422
      | PostAuthCreatepatient500
    >,
    {
      data: PostAuthCreatepatientMutationRequest;
      headers?: PostAuthCreatepatientHeaderParams;
    },
    TContext
  >;

  return useMutation<
    PostAuthCreatepatientMutationResponse,
    ResponseErrorConfig<
      | PostAuthCreatepatient401
      | PostAuthCreatepatient403
      | PostAuthCreatepatient404
      | PostAuthCreatepatient422
      | PostAuthCreatepatient500
    >,
    {
      data: PostAuthCreatepatientMutationRequest;
      headers?: PostAuthCreatepatientHeaderParams;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostAuthCreatepatientMutationResponse,
    ResponseErrorConfig<
      | PostAuthCreatepatient401
      | PostAuthCreatepatient403
      | PostAuthCreatepatient404
      | PostAuthCreatepatient422
      | PostAuthCreatepatient500
    >,
    {
      data: PostAuthCreatepatientMutationRequest;
      headers?: PostAuthCreatepatientHeaderParams;
    },
    TContext
  >;
}
