/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostAuthUploadphotoMutationRequest,
  PostAuthUploadphotoMutationResponse,
  PostAuthUploadphoto400,
  PostAuthUploadphoto422,
  PostAuthUploadphoto500,
} from "../types/PostAuthUploadphoto.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { buildFormData } from "../.kubb/config.ts";

export const postAuthUploadphotoMutationKey = () =>
  [{ url: "/auth/uploadPhoto" }] as const;

export type PostAuthUploadphotoMutationKey = ReturnType<
  typeof postAuthUploadphotoMutationKey
>;

/**
 * @description Recebe uma imagem via multipart/form-data e atualiza o campo imageUrl do usuário no banco.
 * @summary Upload de foto de perfil
 * {@link /auth/uploadPhoto}
 */
export async function postAuthUploadphoto(
  data: PostAuthUploadphotoMutationRequest,
  config: Partial<RequestConfig<PostAuthUploadphotoMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const formData = buildFormData(requestData);
  const res = await request<
    PostAuthUploadphotoMutationResponse,
    ResponseErrorConfig<
      PostAuthUploadphoto400 | PostAuthUploadphoto422 | PostAuthUploadphoto500
    >,
    PostAuthUploadphotoMutationRequest
  >({
    method: "POST",
    url: `/auth/uploadPhoto`,
    data: formData as FormData,
    ...requestConfig,
  });
  return res.data;
}

export function postAuthUploadphotoMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostAuthUploadphotoMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postAuthUploadphotoMutationKey();
  return mutationOptions<
    PostAuthUploadphotoMutationResponse,
    ResponseErrorConfig<
      PostAuthUploadphoto400 | PostAuthUploadphoto422 | PostAuthUploadphoto500
    >,
    { data: PostAuthUploadphotoMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postAuthUploadphoto(data, config);
    },
  });
}

/**
 * @description Recebe uma imagem via multipart/form-data e atualiza o campo imageUrl do usuário no banco.
 * @summary Upload de foto de perfil
 * {@link /auth/uploadPhoto}
 */
export function usePostAuthUploadphoto<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAuthUploadphotoMutationResponse,
      ResponseErrorConfig<
        PostAuthUploadphoto400 | PostAuthUploadphoto422 | PostAuthUploadphoto500
      >,
      { data: PostAuthUploadphotoMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostAuthUploadphotoMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postAuthUploadphotoMutationKey();

  const baseOptions = postAuthUploadphotoMutationOptions(
    config,
  ) as UseMutationOptions<
    PostAuthUploadphotoMutationResponse,
    ResponseErrorConfig<
      PostAuthUploadphoto400 | PostAuthUploadphoto422 | PostAuthUploadphoto500
    >,
    { data: PostAuthUploadphotoMutationRequest },
    TContext
  >;

  return useMutation<
    PostAuthUploadphotoMutationResponse,
    ResponseErrorConfig<
      PostAuthUploadphoto400 | PostAuthUploadphoto422 | PostAuthUploadphoto500
    >,
    { data: PostAuthUploadphotoMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostAuthUploadphotoMutationResponse,
    ResponseErrorConfig<
      PostAuthUploadphoto400 | PostAuthUploadphoto422 | PostAuthUploadphoto500
    >,
    { data: PostAuthUploadphotoMutationRequest },
    TContext
  >;
}
