/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostAuthSendotpMutationRequest,
  PostAuthSendotpMutationResponse,
  PostAuthSendotp422,
  PostAuthSendotp500,
} from "../types/PostAuthSendotp.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postAuthSendotpMutationKey = () =>
  [{ url: "/auth/sendOTP" }] as const;

export type PostAuthSendotpMutationKey = ReturnType<
  typeof postAuthSendotpMutationKey
>;

/**
 * @description Fluxo de registro/login: envia um código OTP para o e-mail passado no body da requisição.
 * @summary Envia código OTP para o e-mail informado
 * {@link /auth/sendOTP}
 */
export async function postAuthSendotp(
  data: PostAuthSendotpMutationRequest,
  config: Partial<RequestConfig<PostAuthSendotpMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostAuthSendotpMutationResponse,
    ResponseErrorConfig<PostAuthSendotp422 | PostAuthSendotp500>,
    PostAuthSendotpMutationRequest
  >({
    method: "POST",
    url: `/auth/sendOTP`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function postAuthSendotpMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostAuthSendotpMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postAuthSendotpMutationKey();
  return mutationOptions<
    PostAuthSendotpMutationResponse,
    ResponseErrorConfig<PostAuthSendotp422 | PostAuthSendotp500>,
    { data: PostAuthSendotpMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postAuthSendotp(data, config);
    },
  });
}

/**
 * @description Fluxo de registro/login: envia um código OTP para o e-mail passado no body da requisição.
 * @summary Envia código OTP para o e-mail informado
 * {@link /auth/sendOTP}
 */
export function usePostAuthSendotp<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAuthSendotpMutationResponse,
      ResponseErrorConfig<PostAuthSendotp422 | PostAuthSendotp500>,
      { data: PostAuthSendotpMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostAuthSendotpMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postAuthSendotpMutationKey();

  const baseOptions = postAuthSendotpMutationOptions(
    config,
  ) as UseMutationOptions<
    PostAuthSendotpMutationResponse,
    ResponseErrorConfig<PostAuthSendotp422 | PostAuthSendotp500>,
    { data: PostAuthSendotpMutationRequest },
    TContext
  >;

  return useMutation<
    PostAuthSendotpMutationResponse,
    ResponseErrorConfig<PostAuthSendotp422 | PostAuthSendotp500>,
    { data: PostAuthSendotpMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostAuthSendotpMutationResponse,
    ResponseErrorConfig<PostAuthSendotp422 | PostAuthSendotp500>,
    { data: PostAuthSendotpMutationRequest },
    TContext
  >;
}
