/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostAppointmentsIdActionsMutationRequest,
  PostAppointmentsIdActionsMutationResponse,
  PostAppointmentsIdActionsPathParams,
  PostAppointmentsIdActionsHeaderParams,
  PostAppointmentsIdActions400,
  PostAppointmentsIdActions401,
  PostAppointmentsIdActions403,
  PostAppointmentsIdActions404,
  PostAppointmentsIdActions409,
  PostAppointmentsIdActions422,
  PostAppointmentsIdActions500,
} from "../types/PostAppointmentsIdActions.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postAppointmentsIdActionsMutationKey = () =>
  [{ url: "/appointments/:id/actions" }] as const;

export type PostAppointmentsIdActionsMutationKey = ReturnType<
  typeof postAppointmentsIdActionsMutationKey
>;

/**
 * @description Paciente cria uma solicitação para um profissional em data/hora escolhidas.
 * @summary Criar solicitação de agendamento (paciente)
 * {@link /appointments/:id/actions}
 */
export async function postAppointmentsIdActions(
  id: PostAppointmentsIdActionsPathParams["id"],
  data: PostAppointmentsIdActionsMutationRequest,
  headers: PostAppointmentsIdActionsHeaderParams,
  config: Partial<RequestConfig<PostAppointmentsIdActionsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostAppointmentsIdActionsMutationResponse,
    ResponseErrorConfig<
      | PostAppointmentsIdActions400
      | PostAppointmentsIdActions401
      | PostAppointmentsIdActions403
      | PostAppointmentsIdActions404
      | PostAppointmentsIdActions409
      | PostAppointmentsIdActions422
      | PostAppointmentsIdActions500
    >,
    PostAppointmentsIdActionsMutationRequest
  >({
    method: "POST",
    url: `/appointments/${id}/actions`,
    data: requestData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function postAppointmentsIdActionsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostAppointmentsIdActionsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postAppointmentsIdActionsMutationKey();
  return mutationOptions<
    PostAppointmentsIdActionsMutationResponse,
    ResponseErrorConfig<
      | PostAppointmentsIdActions400
      | PostAppointmentsIdActions401
      | PostAppointmentsIdActions403
      | PostAppointmentsIdActions404
      | PostAppointmentsIdActions409
      | PostAppointmentsIdActions422
      | PostAppointmentsIdActions500
    >,
    {
      id: PostAppointmentsIdActionsPathParams["id"];
      data: PostAppointmentsIdActionsMutationRequest;
      headers: PostAppointmentsIdActionsHeaderParams;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data, headers }) => {
      return postAppointmentsIdActions(id, data, headers, config);
    },
  });
}

/**
 * @description Paciente cria uma solicitação para um profissional em data/hora escolhidas.
 * @summary Criar solicitação de agendamento (paciente)
 * {@link /appointments/:id/actions}
 */
export function usePostAppointmentsIdActions<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAppointmentsIdActionsMutationResponse,
      ResponseErrorConfig<
        | PostAppointmentsIdActions400
        | PostAppointmentsIdActions401
        | PostAppointmentsIdActions403
        | PostAppointmentsIdActions404
        | PostAppointmentsIdActions409
        | PostAppointmentsIdActions422
        | PostAppointmentsIdActions500
      >,
      {
        id: PostAppointmentsIdActionsPathParams["id"];
        data: PostAppointmentsIdActionsMutationRequest;
        headers: PostAppointmentsIdActionsHeaderParams;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostAppointmentsIdActionsMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postAppointmentsIdActionsMutationKey();

  const baseOptions = postAppointmentsIdActionsMutationOptions(
    config,
  ) as UseMutationOptions<
    PostAppointmentsIdActionsMutationResponse,
    ResponseErrorConfig<
      | PostAppointmentsIdActions400
      | PostAppointmentsIdActions401
      | PostAppointmentsIdActions403
      | PostAppointmentsIdActions404
      | PostAppointmentsIdActions409
      | PostAppointmentsIdActions422
      | PostAppointmentsIdActions500
    >,
    {
      id: PostAppointmentsIdActionsPathParams["id"];
      data: PostAppointmentsIdActionsMutationRequest;
      headers: PostAppointmentsIdActionsHeaderParams;
    },
    TContext
  >;

  return useMutation<
    PostAppointmentsIdActionsMutationResponse,
    ResponseErrorConfig<
      | PostAppointmentsIdActions400
      | PostAppointmentsIdActions401
      | PostAppointmentsIdActions403
      | PostAppointmentsIdActions404
      | PostAppointmentsIdActions409
      | PostAppointmentsIdActions422
      | PostAppointmentsIdActions500
    >,
    {
      id: PostAppointmentsIdActionsPathParams["id"];
      data: PostAppointmentsIdActionsMutationRequest;
      headers: PostAppointmentsIdActionsHeaderParams;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostAppointmentsIdActionsMutationResponse,
    ResponseErrorConfig<
      | PostAppointmentsIdActions400
      | PostAppointmentsIdActions401
      | PostAppointmentsIdActions403
      | PostAppointmentsIdActions404
      | PostAppointmentsIdActions409
      | PostAppointmentsIdActions422
      | PostAppointmentsIdActions500
    >,
    {
      id: PostAppointmentsIdActionsPathParams["id"];
      data: PostAppointmentsIdActionsMutationRequest;
      headers: PostAppointmentsIdActionsHeaderParams;
    },
    TContext
  >;
}
