/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/libs/kubbClient";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/libs/kubbClient";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostAuthUploadphotoMutationResponse,
  PostAuthUploadphotoHeaderParams,
  PostAuthUploadphoto400,
  PostAuthUploadphoto401,
  PostAuthUploadphoto403,
  PostAuthUploadphoto404,
  PostAuthUploadphoto422,
  PostAuthUploadphoto500,
} from "../types/PostAuthUploadphoto.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postAuthUploadphotoMutationKey = () =>
  [{ url: "/auth/uploadPhoto" }] as const;

export type PostAuthUploadphotoMutationKey = ReturnType<
  typeof postAuthUploadphotoMutationKey
>;

/**
 * @description Recebe uma imagem via multipart/form-data e atualiza o campo imageUrl do usuário no banco.
 * @summary Upload de foto de perfil
 * {@link /auth/uploadPhoto}
 */
export async function postAuthUploadphoto(
  headers: PostAuthUploadphotoHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostAuthUploadphotoMutationResponse,
    ResponseErrorConfig<
      | PostAuthUploadphoto400
      | PostAuthUploadphoto401
      | PostAuthUploadphoto403
      | PostAuthUploadphoto404
      | PostAuthUploadphoto422
      | PostAuthUploadphoto500
    >,
    unknown
  >({
    method: "POST",
    url: `/auth/uploadPhoto`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}

export function postAuthUploadphotoMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = postAuthUploadphotoMutationKey();
  return mutationOptions<
    PostAuthUploadphotoMutationResponse,
    ResponseErrorConfig<
      | PostAuthUploadphoto400
      | PostAuthUploadphoto401
      | PostAuthUploadphoto403
      | PostAuthUploadphoto404
      | PostAuthUploadphoto422
      | PostAuthUploadphoto500
    >,
    { headers: PostAuthUploadphotoHeaderParams },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ headers }) => {
      return postAuthUploadphoto(headers, config);
    },
  });
}

/**
 * @description Recebe uma imagem via multipart/form-data e atualiza o campo imageUrl do usuário no banco.
 * @summary Upload de foto de perfil
 * {@link /auth/uploadPhoto}
 */
export function usePostAuthUploadphoto<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAuthUploadphotoMutationResponse,
      ResponseErrorConfig<
        | PostAuthUploadphoto400
        | PostAuthUploadphoto401
        | PostAuthUploadphoto403
        | PostAuthUploadphoto404
        | PostAuthUploadphoto422
        | PostAuthUploadphoto500
      >,
      { headers: PostAuthUploadphotoHeaderParams },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postAuthUploadphotoMutationKey();

  const baseOptions = postAuthUploadphotoMutationOptions(
    config,
  ) as UseMutationOptions<
    PostAuthUploadphotoMutationResponse,
    ResponseErrorConfig<
      | PostAuthUploadphoto400
      | PostAuthUploadphoto401
      | PostAuthUploadphoto403
      | PostAuthUploadphoto404
      | PostAuthUploadphoto422
      | PostAuthUploadphoto500
    >,
    { headers: PostAuthUploadphotoHeaderParams },
    TContext
  >;

  return useMutation<
    PostAuthUploadphotoMutationResponse,
    ResponseErrorConfig<
      | PostAuthUploadphoto400
      | PostAuthUploadphoto401
      | PostAuthUploadphoto403
      | PostAuthUploadphoto404
      | PostAuthUploadphoto422
      | PostAuthUploadphoto500
    >,
    { headers: PostAuthUploadphotoHeaderParams },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostAuthUploadphotoMutationResponse,
    ResponseErrorConfig<
      | PostAuthUploadphoto400
      | PostAuthUploadphoto401
      | PostAuthUploadphoto403
      | PostAuthUploadphoto404
      | PostAuthUploadphoto422
      | PostAuthUploadphoto500
    >,
    { headers: PostAuthUploadphotoHeaderParams },
    TContext
  >;
}
