name: CI / Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Install dependencies
      run: npm ci

    - name: Lint 🧹
      run: npm run lint

    - name: Run unit tests (Jest) 🧪
      run: npm test -- --watchAll=false

    - name: Run Storybook checks (optional) 🎨
      run: npm run storybook:build

    - name: Run E2E tests (Cypress) 🔥
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
